### ISSUE TITLE
Cannot set breakpoint to instance method name in namespaced class

### ISSUE THREAD

**Issue by mjonckiere** [deivid-rodriguez/byebug#106]
gem version : 3.5.1

When setting a breakpoint using a method name, it does not seem possible to specify an instance method that belongs to a namespaced class (filename redacted) : 

```
(byebug) break Rails::Application#call
SyntaxError Exception: xxx.rb:xx: syntax error, unexpected end-of-input, expecting tSTRING_CONTENT or tSTRING_DBEG or tSTRING_DVAR or tSTRING_END
Rails:
      ^
*** Unknown class Rails:
```

This would be really useful, especially when debugging code inside gems (where you cannot drop a `byebug` freely). Maybe am I missing something ? Surrounding the string in quotes does not work either.

__EDIT__

my bad, this works when using only one colon : 

```
(byebug) break Rails:Application#call
Created breakpoint 1 at Rails::Application#call
```

Still, this syntax seems a bit misleading.

**Comment by deivid-rodriguez** [comment]
Yes, right. That's not currently possible. I'll leave this opened in case me or someone wants to implement this in the future.

In the meantime, use the `file:line` syntax.

**Comment by mjonckiere** [comment]
the culprit seems to be `POSITION_REGEXP` in `Byebug::BreakCommand`. I'll have a look at it if I have time.

**Comment by deivid-rodriguez** [comment]
Yes, that's a good starting point! If you try this and get stuck let me know!

**Comment by deivid-rodriguez** [comment]
> my bad, this works when using only one colon :

I would be very surprised... is it really working?? Or it's just not giving you any errors?

**Comment by mjonckiere** [comment]
Not giving any errors... did not try further at that time, because I found another way around my problem. 

I think the regexp captures the wrong things. I Have a regexp that seems to work, but did not proceed to implement it yet : 

```ruby
regex = /
  (?<command>b(reak)*)\s+  
  (?<args> 
     (?<file>.+)*:(?<line>\d+)   
     |   
     (?<target>.+)(?<operator>[#\.])(?<method>.+) 
  )
/x

match = regex.match('break Foo::Bar.baz')
match[:command] # => 'break'
match[:target] # => 'Foo::Bar'
match[:operator] # => '.'
match[:method] # => 'baz'

match = regex.match('break :42')
match[:line] # => '42'

match = regex.match('break foo.rb:42')
match[:file] # => 'foo.rb'
match[:line] # => '42'
```

**Comment by deivid-rodriguez** [comment]
I've finally fixed this, could you give last master a try and let me know?
