### ISSUE TITLE
Confusing behavior of breaks command

### ISSUE THREAD

**Issue by everm1nd** [deivid-rodriguez/byebug#109]
byebug have a commands `break` and `breaks`. With `break` you can delete breakpoint doing this:

`break --delete N`

After deletion it types list of all remaining breakpoints. But when you type `breaks --delete N` it does not respect `--delete` flag and show no error messages. Just typing the same output - list of all available breakpoints. For my it was a little bit confusing. Maybe it's better to throw error or implement `--delete` flag support for `breaks`.

**Comment by deivid-rodriguez** [comment]
Hi @everm1nd, I agree with you, but you got the repository wrong... This is a `pry-byebug` issue. Could you reopen the issue there?

**Comment by everm1nd** [comment]
@deivid-rodriguez Sure. Sorry for that mess.

**Comment by deivid-rodriguez** [comment]
@everm1nd No problem!
