### ISSUE TITLE
remote debugging?

### ISSUE THREAD

**Issue by mcfiredrill** [deivid-rodriguez/byebug#11]
Is there any sort of support for remote debugging? It would be nice if I could debug programs that were started with say, foreman.

**Comment by kyledcline** [comment]
I know this was closed a long time ago, but I cannot get byebug to work with foreman. The byebug prompt shows up and then is swallowed by foreman logging output.

As @Emerson said, are there any docs or troubleshooting help?

**Comment by deivid-rodriguez** [comment]
Have a look at #59 and #63... :(

I'm planning to improve the docs soon, but for now there's [this](https://github.com/deivid-rodriguez/byebug/blob/master/GUIDE.md#debugging-remote-programs)

**Comment by kyledcline** [comment]
Thanks @deivid-rodriguez

**Comment by deivid-rodriguez** [comment]
:+1:

**Comment by Startouf** [comment]
Do we just need to allow inbound TCP on the port we open ? I'm trying to configure my AWS security Group to get it right...
