### ISSUE TITLE
 Byebug's stacksize error

### ISSUE THREAD

**Issue by mailbaoer** [deivid-rodriguez/byebug#110]
hello，when I used byebug on my rails project,it occur to me the errors
Connecting... 
Connected
*** Byebug's stacksize (1) should be 4. This might be a bug in byebug or ruby's debugging API's

Anyone know how to solve this problem? My ruby version is 2.1.2 and rails version is 4.1.7

**Comment by deivid-rodriguez** [comment]
Hi, this is an old warning that will be removed in byebug 4.0.0.

If you want to get rid of it now, use latest byebug's master (add `gem 'byebug' , github: 'deivid-rodriguez/byebug'` to your Gemfile and run `bundle update byebug`)

**Comment by mailbaoer** [comment]
cool, it works, thank you very much!

**Comment by deivid-rodriguez** [comment]
:wink:
