### ISSUE TITLE
Byebug stops catching at breakpoint

### ISSUE THREAD

**Issue by jbrodie** [deivid-rodriguez/byebug#112]
I have been working along fine and all of a sudden byebug fails to catch at a breakpoint.

I don't know what I did, or how to get this corrected, or even how to replicate, I am just curious if others have come into this and what was done to repair it.

I have updated the gem to the most recent, full restart on machine and nothing.

Ruby 2.1.1 on Rails 4.0.4.

Anyone?

**Comment by deivid-rodriguez** [comment]
@jbrodie This needs more info... Closing until a better report is made.
