### ISSUE TITLE
debug a console command

### ISSUE THREAD

**Issue by cooledge** [deivid-rodriguez/byebug#121]
When I am debugging code, sometimes I want to type a ruby expression and have the debugger run on that command so I can see what is happening inside. For this case what I do now is stop the debugger and add the line into the source with a breakpoint in front of it and then rerun my tests. It would be cool if I could have a command like "debug <expression>" which would run <expression> and act as if a breakpoint was set on it.

**Comment by deivid-rodriguez** [comment]
Thanks @cooledge, I'll think about this.

**Comment by akostadinov** [comment]
+1 here, it's very useful to use sub-debuggers. Especially when used in the pry-byebug combo. At the moment I'm mostly using pry and only sometimes byebug when debugging commands are important.

**Comment by deivid-rodriguez** [comment]
Just pushed a fixed to this. Not providing a new command, but just making it work by default.
