### ISSUE TITLE
OSX build broken against ruby-head

### ISSUE THREAD

**Issue by deivid-rodriguez** [deivid-rodriguez/byebug#126]
__OSX__ build against __ruby-head__ has been broken for some days.

This is not a priority as __ruby 2.3__ won't be released until the end of the year, but I'm opening this in case someone with an OSX machine available wants to `git bisect` this and find the offending commit in __ruby-core__. I'll help anybody willing to contribute.

**Comment by nritholtz** [comment]
Hey @deivid-rodriguez , I got a Macbook. If you can walk me through it, I don't mind helping out.

**Comment by deivid-rodriguez** [comment]
@nritholtz Thanks for the help.

I was getting [some stuff ready](https://gist.github.com/deivid-rodriguez/7be3d6465d80dc4bf97d) to help you `git bisect` this issue but I eventually realized that this is not `byebug`'s fault. `ruby-head` version in travis OSX actually points to

    ruby 2.2.0dev (2014-12-03 trunk 48697) [x86_64-darwin13]

That Ruby is very outdated, actually prior to `ruby 2.2.0`...! So this is not actually an issue.
