### ISSUE TITLE
No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by kamen-hursev** [deivid-rodriguez/byebug#128]
I just upgraded to buybug 4.0.0 I and get this error:
`No such file or directory @ rb_sysopen - /home/khursev/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/byebug-4.0.0/lib/byebug/printers/texts/plain.yml` 
instead of the debugging console when execution reaches `buybug` in the code.

Ubuntu version: Ubuntu 14.04.2 LTS
Ruby version: 2.2.0
Please tell me if you need more information.

**Comment by deivid-rodriguez** [comment]
Uups, sorry about that. It should be fixed in `4.0.1`.

**Comment by kamen-hursev** [comment]
Yes, it's fixed. Thanks!
