### ISSUE TITLE
4.0.1 Broken on Windows

### ISSUE THREAD

**Issue by betam4x** [deivid-rodriguez/byebug#129]
byebug 4.0.1 is broken on Windows.

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

C:/Ruby21-x64/bin/ruby.exe -r ./siteconf20150313-10752-1hz6nzd.rb extconf.rb
C:/Ruby21-x64/bin/ruby.exe: No such file or directory -- extconf.rb (LoadError)

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/byebug-4.0.1 for inspection.
Results logged to C:/Ruby21-x64/lib/ruby/gems/2.1.0/extensions/x64-mingw32/2.1.0/byebug-4.0.1/gem_make.out
An error occurred while installing byebug (4.0.1), and Bundler cannot continue.
Make sure that `gem install byebug -v '4.0.1'` succeeds before bundling.
```

3.5.1 works fine.

**Comment by deivid-rodriguez** [comment]
:cry: 

The CI build seems fine... at least in the Ruby you're using (in Ruby 2.2 it seems that something is wrong in the appveyor's server ...).

If you want to and have time, could you `git bisect` this from 3.5.1? I don't have a Windows machine...

**Comment by deivid-rodriguez** [comment]
Another idea. Clone the gem and replace the `extconf.rb` file with the one present in '3.5.1'. Then link to the cloned gem in your application and try to install it.

Let me know if you need any help (if you want to help at all, of course).

**Comment by betam4x** [comment]
Did some troubleshooting, turns out Ruby doesn't like autorun on windows for the command prompt.  Not a byebug issue.  Sorry about that!

**Comment by deivid-rodriguez** [comment]
No problem, thanks for checking that out!
