### ISSUE TITLE
4.0.1 and 4.0.2 not building on SuSE Enterprise 11

### ISSUE THREAD

**Issue by laneatomic** [deivid-rodriguez/byebug#130]
I'm receiving the below build errors on SLES with Ruby 2.1.5 installed via rbenv. Previously we were using 3.5.1 which built successfully.

    Building native extensions.  This could take a while...
    ERROR:  Error installing byebug:
      ERROR: Failed to build gem native extension.

        /home/digopuser/.rbenv/versions/2.1.5/bin/ruby -r ./siteconf20150318-62725-1803d7a.rb extconf.rb
    creating Makefile

    make "DESTDIR=" clean

    make "DESTDIR="
    compiling locker.c
    compiling context.c
    cc1: warnings being treated as errors
    context.c: In function ‘dt_inherited’:
    context.c:629: error: unused parameter ‘klass’
    make: *** [context.o] Error 1

    make failed, exit code 2

    Gem files will remain installed in /home/digopuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/byebug-4.0.1 for inspection.
    Results logged to /home/digopuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0-static/byebug-4.0.1/gem_make.out

**Comment by chrisjensen** [comment]
I'm seeing the same thing on OSX 10.6, running ruby 2.0.0p598

**Comment by deivid-rodriguez** [comment]
Is `4.0.3` working?

**Comment by laneatomic** [comment]
Yep! That works on a gem install. I've updated our Gemfile to include 4.0.3 and am testing our build now. Hopefully this doesn't break again. :four_leaf_clover:

**Comment by laneatomic** [comment]
Yep, we're all good. Thanks for the update!

**Comment by deivid-rodriguez** [comment]
Great!

Out of curiosity, are you installing `byebug` in your CI environment? It's generally better not to do that unless there's a reason.

**Comment by laneatomic** [comment]
No, it's used in our development. Thanks for the heads-up though!

**Comment by deivid-rodriguez** [comment]
:+1:
