### ISSUE TITLE
frame command doesn't work with negative number

### ISSUE THREAD

**Issue by ark6** [deivid-rodriguez/byebug#136]
[GUIDE.md](https://github.com/deivid-rodriguez/byebug/blob/master/GUIDE.md) says that 
when frame command is typed with negative number, outermost stack frame is shown.

However, in practice, nothing is displayed, and doesn't move to the frame I specify with the argument.
Is this a bug ?
(using ruby 2.2.1p85 and byebug 4.0.5.)

**Comment by deivid-rodriguez** [comment]
Bug/Feature doesn't matter, I'd like this to work as stated in the Guide.

Do you want to try a PR? It should be an easy one and I can help if necessary.

**Comment by ark6** [comment]
Yes, I want to try it.

**Comment by deivid-rodriguez** [comment]
This is where the magic happens and where you'll probably need to apply the fix: https://github.com/deivid-rodriguez/byebug/blob/master/lib/byebug/helpers/frame.rb#L7-48

And this is where the command is implemented and calls those methods: https://github.com/deivid-rodriguez/byebug/blob/master/lib/byebug/commands/frame.rb#L29

Thanks!

**Comment by ark6** [comment]
Thanks for the info.

**Comment by deivid-rodriguez** [comment]
Thanks a lot for your work @ark6, closing.
