### ISSUE TITLE
How to list all commands ?

### ISSUE THREAD

**Issue by rusikf** [deivid-rodriguez/byebug#140]
I want't to list all commands like in pry
```
[1] pry(main)> help
Help
  help               Show a list of commands or information about a specific command.

Context
  cd                 Move into a new context (object or scope).
  find-method        Recursively search for a method within a class/module or the current namespace.
  ls                 Show the list of vars and methods in the current scope.
  pry-backtrace      Show the backtrace for the pry session.
  raise-up           Raise an exception out of the current pry instance.
  reset              Reset the repl to a clean state.
  watch              Watch the value of an expression and print a notification whenever it changes.
  whereami           Show code surrounding the current context.
  wtf?               Show the backtrace of the most recent exception.
...
```
Is it possible in byebug? I want to list ALL commands with desc, it it really helpfull for me, because now, if you type help you have
```
(byebug) help

  h[elp][ <cmd>[ <subcmd>]]

  help                -- prints this help.
  help <cmd>          -- prints help on command <cmd>.
  help <cmd> <subcmd> -- prints help on <cmd>'s subcommand <subcmd>.

```

**Comment by deivid-rodriguez** [comment]
It's not currently possible, but I like `pry`'s behavior better as you do. Feel free to submit a PR.

**Comment by sampierson** [comment]
I seem to recall you could do this in the past.  Am I remembering incorrectly or was there a "?" command that listed all the commands?

**Comment by deivid-rodriguez** [comment]
I think you are remembering incorrectly.

**Comment by sampierson** [comment]
Ok.
I found this.  Very useful: http://fleeblewidget.co.uk/2014/05/byebug-cheatsheet/

**Comment by nijotz** [comment]
@deivid-rodriguez curious, why is it not currently possible? And if it's not possible, how would I go about doing this and submitting a PR?

**Comment by deivid-rodriguez** [comment]
@nijotz I've been working on this, will commit the fix soon.

**Comment by nijotz** [comment]
nice! :beer:

**Comment by amikula** [comment]
Great news @deivid-rodriguez! It's frustrating to have to come back to the README every time I want to look at a command. Let me know if you need help on this.

FWIW, there used to be a list of commands (without descriptions) in 3.5.1. That was removed in f492dbb5697c.

**Comment by deivid-rodriguez** [comment]
Yes, I noticed it while implementing this back. This is already coded, I'm just waiting to find some time to clean it up and push it cause it ended up requiring more changes than I expected.

**Comment by deivid-rodriguez** [comment]
This is now available in latest master!
