### ISSUE TITLE
issue while installing byebug 

### ISSUE THREAD

**Issue by RohithEngu** [deivid-rodriguez/byebug#143]
I am Getting the below error:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    A:/Ruby/Ruby22/bin/ruby.exe -r ./siteconf20150513-3844-77jc0f.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating byebug-i386-mingw32.def
compiling breakpoint.c
cc1.exe: warnings being treated as errors
In file included from a:/Ruby/Ruby22/include/ruby-2.2.0/ruby/defines.h:163:0,
                 from a:/Ruby/Ruby22/include/ruby-2.2.0/ruby/ruby.h:29,
                 from a:/Ruby/Ruby22/include/ruby-2.2.0/ruby.h:33,
                 from ./byebug.h:4,
                 from breakpoint.c:1:
a:/Ruby/Ruby22/include/ruby-2.2.0/ruby/win32.h:319:44: error: 'struct timespec' declared inside parameter list
a:/Ruby/Ruby22/include/ruby-2.2.0/ruby/win32.h:319:44: error: its scope is only this definition or declaration, which is probably not what you want
a:/Ruby/Ruby22/include/ruby-2.2.0/ruby/win32.h:320:43: error: 'struct timespec' declared inside parameter list
make: *** [breakpoint.o] Error 1

make failed, exit code 2

Gem files will remain installed in A:/Ruby/Ruby22/lib/ruby/gems/2.2.0/gems/byebug-4.0.5 for inspection.
Results logged to A:/Ruby/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/byebug-4.0.5/gem_make.out
An error occurred while installing byebug (4.0.5), and Bundler cannot continue.
Make sure that `gem install byebug -v '4.0.5'` succeeds before bundling.
-----------------------------
Gem Environment: 
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5
  - RUBY VERSION: 2.2.2 (2015-04-13 patchlevel 95) [i386-mingw32]
  - INSTALLATION DIRECTORY: A:/Ruby/Ruby22/lib/ruby/gems/2.2.0
  - RUBY EXECUTABLE: A:/Ruby/Ruby22/bin/ruby.exe
  - EXECUTABLE DIRECTORY: A:/Ruby/Ruby22/bin
  - SPEC CACHE DIRECTORY: C:/Users/ROHITHENGU/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-mingw32
  - GEM PATHS:
     - A:/Ruby/Ruby22/lib/ruby/gems/2.2.0
     - C:/Users/ROHITHENGU/.gem/ruby/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Windows\System32
     - C:\Windows
     - A:\Ruby\Ruby22\bin
     - C:\Program Files\MySQL\MySQL Server 5.6\bin
     - A:\Ruby\Ruby22\devkit

**Comment by deivid-rodriguez** [comment]
Hi @RohithEngu . I'm really sorry I didn't reply to this early. I don't think this is a problem in Byebug actually (the error happens inside Ruby sources). I think this is due to some problem with your Ruby/DevKit installation. Can you have a look at #119 and see if you can fix it with the advice given there?

**Comment by deivid-rodriguez** [comment]
Closing for lack of feedback.

**Comment by zahidzia** [comment]
I am having the same error... which is different for #119 and I also tried reinstalling the DevKit

**Comment by deivid-rodriguez** [comment]
@zahidzia I'm sorry I can't be of more help, the error points to an installation problem, but I know nothing about Ruby in Windows.

**Comment by clgoro** [comment]
@deivid-rodriguez hi Deivid I've tried to install byebug in a mac and now I cannot use rails. It is asking 
An error occurred while installing byebug (9.1.0), and Bundler cannot
continue.
Make sure that `gem install byebug -v '9.1.0'` succeeds before bundling.
is there a solution for this problem?

**Comment by deivid-rodriguez** [comment]
@clgoro Usually installation problems are due to some problem in your Ruby installation, but I'm not sure... Sorry I can't be of more help.
