### ISSUE TITLE
Byebug thread handling

### ISSUE THREAD

**Issue by ccoupe** [deivid-rodriguez/byebug#146]
I'd like to use byebug in the project I'm working which is a cross platform GUI, with an embedded Ruby  https://github.com/Shoes3/shoes3.  The 'remote' interface does work but it's not as useful as the terminal based interface. Since Shoes is a GUI, there is no terminal. I do have a Shoes/Ruby level GUI window that does satisfy the byebug interface (puts, readline, etc) it uses a couple of Ruby threads and I believe byebug shuts those down.   Assuming that is true, is there some way to tell byebug to let some Ruby threads run?

Currently I am attempting to start byebug with this:
```
     @byethr = Thread.new {
          Byebug.debug_load($PROGRAM_NAME, true) # this starts byebug loop
```
see https://github.com/Shoes3/shoes3/blob/master/lib/shoes/debugger.rb

**Comment by os97673** [comment]
perhaps you should try debugger-xml+byebug for this.

**Comment by ccoupe** [comment]
Oleg, thanks for the info. Shoes is pretty unique in how it does things, for better or for worse. User scripts are loaded and run inside Shoes in a new Ruby thread (perhaps) and not a in separate os level process like most IDE would do.

**Comment by deivid-rodriguez** [comment]
@ccoupe I'm so sorry for taking this long to reply. Yes, `byebug` shuts shutdown every thread before giving back a prompt to the user. There's a special `Thread` subclass that is ignored. I think it's called `DebugThread`.

Hope it helps.

**Comment by ccoupe** [comment]
@deivid-rodriguez .  I did find DebugThread earlier but my problem is actually more difficult - Ruby is run on the Gtk thread which has to be blocked by byebug.  Fortunately, byebug can be used if the user launches Shoes from a terminal/console in Linux, OSX, and Windows so that's good enough.
