### ISSUE TITLE
Will not stop at breakpoints with symlinks involved in directories

### ISSUE THREAD

**Issue by brettwilliams** [deivid-rodriguez/byebug#147]
I am working in linux/x86_64 with ruby 2.1.6.  A simple ruby script is in a directory which looks like this:
```sh
>> cd $HOME
>> pwd
/home/brettw
>> tree simple_ruby/
simple_ruby/
|-- bin
|   `-- simple_run
`-- run_dir

2 directories, 1 file

>> ll simple_link
lrwxrwxrwx 1 brettw design 11 Jun 17 23:01 simple_link -> simple_ruby
>> cd simple_ruby/run_dir/
/home/brettw/simple_ruby/run_dir
```
I then call this program via PATH in two ways, first with the direct path, and secondly through the symlink.  The first one works as expected, the second does not.  You can see that if I do so with the symlink, that breakpoints do not fire.
```ruby
>> PATH=$PATH:$HOME/simple_ruby/bin simple_run
Starting simple program with $0 = /home/brettw/simple_ruby/bin/simple_run

[2, 11] in /home/brettw/simple_ruby/bin/simple_run
    2: 
    3: require 'byebug'
    4: 
    5: puts "Starting simple program with $0 = #{$0}"
    6: byebug
    7: 
=>  8: var = 33
    9: puts "Set a variable"
   10: 
   11: puts "Done"
(byebug) break 9 
Successfully created breakpoint with id 1
(byebug) c
Stopped by breakpoint 1 at /home/brettw/simple_ruby/bin/simple_run:9

[2, 11] in /home/brettw/simple_ruby/bin/simple_run
    2: 
    3: require 'byebug'
    4: 
    5: puts "Starting simple program with $0 = #{$0}"
    6: byebug
    7: 
    8: var = 33
=>  9: puts "Set a variable"
   10: 
   11: puts "Done"
(byebug) c
Set a variable
Done
```
Now for the second run, where I call it using PATH through a symlinked directory:
```ruby
>> pwd
/home/brettw/simple_ruby/run_dir
>> PATH=$PATH:$HOME/simple_link/bin simple_run
Starting simple program with $0 = /home/brettw/simple_link/bin/simple_run

[2, 11] in /home/brettw/simple_link/bin/simple_run
    2: 
    3: require 'byebug'
    4: 
    5: puts "Starting simple program with $0 = #{$0}"
    6: byebug
    7: 
=>  8: var = 33
    9: puts "Set a variable"
   10: 
   11: puts "Done"
(byebug) break 9
Successfully created breakpoint with id 1
(byebug) c
Set a variable
Done
```

Note that this is further complicated by the fact that even cutting and pasting the file and line number that byebug thinks it is currently on (i.e. when hitting an explicit `byebug` statement) will not give the correct result.

If all symlinks are resolved, it seems to work ok.

Is there a way to make this work better, or a best practice that I can follow?

Thank you for your contribution and consideration.

**Comment by deivid-rodriguez** [comment]
@brettwilliams Sorry I totally missed this issue. Great report, thanks! If you want to give it a try, this shouldn't be a really hard one to tackle!

**Comment by os97673** [comment]
@deivid-rodriguez just to share our experience with debugging symlinked files.  Tracepoint API report file name which was used when the file was loaded first time.  In some cases it will be symlinked name in others - real (non-symlinked) name.  In ruby-debug-ide/debase we always use resolved name to make this work reliably.  Hope this will be useful for you.

**Comment by deivid-rodriguez** [comment]
@os97673 Thanks a lot, your input an experience with the other ruby debugging tools is always appreciated.

@brettwilliams Could you try latest master and see if it fixes your issue? I've added a possible fix following @os97673 advice but was too lazy to check if it works or write a test...

**Comment by os97673** [comment]
> @os97673 Thanks a lot, your input an experience with the other ruby debugging tools is always appreciated.

any time :)

**Comment by brettwilliams** [comment]
I'll try to check when I'm able.  I'm pretty sure that the normalize files
method already present is all that is needed since it looks like it does
exactly what is needed

**Comment by brettwilliams** [comment]
Deivid,

Attempt #147 commit fixes the issue in my small test case.  Thanks!

**Comment by deivid-rodriguez** [comment]
@brettwilliams I missed this message and I've done a couple other changes in that area. Could you try, again, against last master and if fixed, close this issue? Thanks a lot!

**Comment by brettwilliams** [comment]
@deivid-rodriguez latest master passes test
