### ISSUE TITLE
Several frame Exceptions

### ISSUE THREAD

**Issue by clarsonneur** [deivid-rodriguez/byebug#148]
Hi, 

Currently debugging with byebug (V5.0.0 on ruby 2.0.0p353), I got several different frame exception error:
(byebug) n
ERROR!!!: Exception RuntimeError: Destination frame (0) is out of range (-10)
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/commands/next.rb:24:in `step_over'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/commands/next.rb:24:in `execute'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:144:in `one_cmd'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:114:in `repl'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:97:in `process_commands'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:48:in `at_line'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/context.rb:90:in `at_line'

OR

(byebug) c
ERROR!!!: Exception RuntimeError: You want to finish 2 frames, but stack size is only -9
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/attacher.rb:17:in `step_out'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/attacher.rb:17:in `attach'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/attacher.rb:28:in `byebug'
/home/larsonsh/.gem/ruby/gems/lorj-1.0.13/lib/core/lorj_basecontroller.rb:195:in `_get_from'

OR

(byebug) c
ERROR!!!: Exception RuntimeError: You want to finish 2 frames, but stack size is only -14
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/attacher.rb:17:in `step_out'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/attacher.rb:17:in `attach'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/attacher.rb:28:in `byebug'
/home/larsonsh/.gem/ruby/gems/lorj-1.0.13/lib/core/lorj_basecontroller.rb:195:in `_get_from'

OR

(byebug) n
ERROR!!!: Exception RuntimeError: Destination frame (0) is out of range (-7)
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/commands/next.rb:24:in `step_over'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/commands/next.rb:24:in `execute'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:144:in `one_cmd'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:114:in `repl'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:97:in `process_commands'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/processors/command_processor.rb:48:in `at_line'
/home/larsonsh/.gem/ruby/gems/byebug-5.0.0/lib/byebug/context.rb:90:in `at_line'

Is it something that you are aware?

**Comment by deivid-rodriguez** [comment]
Yes. Use an up to date Ruby. Recommended versions in the README.
