### ISSUE TITLE
IDE Support

### ISSUE THREAD

**Issue by cfis** [deivid-rodriguez/byebug#15]
I'd like to use byebug with RubyMine.  RubyMine ships with debase, and uses ruby-debug-ide to talk to it.

I have been able to hack my way to get RubyMine to load byebug instead of debase, but then the IDE times out when trying to create a remote debugging connection.

I think this is probably pretty close to working...Anyway, here are my hacked changed to ruby-debug-ide.rb starting at line 8.

<pre>
  #require 'debase'
  require 'byebug'

  module Byebug
    class &lt;&lt; self
      # Called by ruby-debug-ide, code copied from debase
      attr_accessor :keep_frame_binding
    end

    class Command
      # Called by ruby-debug-ide
      def self.control
        # The AddBreakpoint command (where is that coming from) doesn't understand allow_in_control
        if respond_to?(:allow_in_control)
          allow_in_control
        else
          false
        end
      end
    end

    # Called by ruby-debug-ide, code copied from debase
    class DebugThread &lt; Thread
      def self.inherited
        raise RuntimeError.new("Can't inherit Debugger::DebugThread class")
      end
    end
  end

  # Code copied from debase
  ::Debugger = ::Byebug
end
</pre>

**Comment by deivid-rodriguez** [comment]
@astashov New version released! What's next? :)

**Comment by oliverwilkie** [comment]
+1 for Rubymine support

**Comment by dmitry** [comment]
:+1: from another RubyMine user.

**Comment by openscript** [comment]
Took me hours to figure out what caused this problem.

**Comment by os97673** [comment]
we are working on making debugger-xml and byebug compatible, hope you will be able to use it in RubyMine 7.1.1(or 7.1.2 ;) )

**Comment by dborovsky** [comment]
+1 for Rubymine support!

**Comment by deivid-rodriguez** [comment]
I think support is already there since byebug 5.0. @astashov could you please confirm and close this if positive?

**Comment by os97673** [comment]
Currently you can try to use byebug with RubyMine 7.1.3, but there are some problems, I'd call current state as beta.  So, I'd suggest to try it and report problems (to debugger-xml)

**Comment by deivid-rodriguez** [comment]
Ok, closing this then.

**Comment by dborovsky** [comment]
After run debug, error: undefined method '+'. 
I use byebug 5.0.0, 
rubymine 7.1.3, 
OS ubuntu, 
ruby 2.2.1p85 (2015-02-26 revision 49769) [i686-linux], 
Rails 4.2.1

**Comment by os97673** [comment]
> After run debug, error: undefined method '+'. 
> I use byebug 5.0.0, 
> rubymine 7.1.3, 
> OS ubuntu, 
> ruby 2.2.1p85 (2015-02-26 revision 49769) [i686-linux], 
> Rails 4.2.1

please file a ticket agains debugger-xml and provide verbose output of debugger.

**Comment by fabricioftg** [comment]
+1 
byebug 5.0.0
rubymine 8
ubuntu
ruby 2.1.1p76 
rails 4.2.2

**Comment by micheleps** [comment]
@cfis great topic. Can you explain how to do so in the newest rubymine + byebug versions?

**Comment by dmitry** [comment]
@micheleps it should work out of the box, at least for me it works with latest ruby and byebug versions.

**Comment by paramasivam2186** [comment]
@micheleps Can you please help me out to run Pry-byebug with Rubymine Run window?

Downloaded RubyMine 2018.1 version,I could not run pry command, execution stop till binding.pry then I enter continue/next, the command is not working for me.
