### ISSUE TITLE
Control Connection don't work anymore with normal connection

### ISSUE THREAD

**Issue by rhapsodyv** [deivid-rodriguez/byebug#150]
Hi,

I think there is a typo here:
https://github.com/deivid-rodriguez/byebug/commit/90cdfcc9cee8ba6362bad2185390cbe4fa85845d

I have commeted the line with the error.
Pull request: https://github.com/deivid-rodriguez/byebug/pull/151

**Comment by rhapsodyv** [comment]
merged

**Comment by deivid-rodriguez** [comment]
:+1:
