### ISSUE TITLE
How to disable call to 'byebug' from code?

### ISSUE THREAD

**Issue by cheunghy** [deivid-rodriguez/byebug#155]
How to disable call to 'byebug' from code just like `disable breakpoints`?

**Comment by deivid-rodriguez** [comment]
Hi @cheunghy 

The idea is that you have to remove the line or move it somewhere else (note that there's some issues with it, see https://github.com/deivid-rodriguez/byebug/issues/120). If you don't want to call `byebug` from code at all, you can run your program through byebug's runner (`byebug your_program.rb`).
