### ISSUE TITLE
byebug gets confused about stack frame count when next/return/retry/... gets called in a rescue block

### ISSUE THREAD

**Issue by doudou** [deivid-rodriguez/byebug#156]
This really is so that others won't spend time debugging it again ... It is fixed on ruby 2.1.6 and 2.2.2. 2.1.2 is affected (which, unfortunately, is also ubuntu 15.04's ruby version)

A little example:

~~~ ruby
def a
    1.times do
        begin
            raise RuntimeError
        rescue
            next
        end
    end
end

Byebug.verbose = true
byebug
a
~~~

outputs (I've patched byebug to show the frame number for clarity)

~~~
  [f#1 t#1] call@../../../test.rb:11 Object#a
   [f#2 t#1] line@../../../test.rb:12 Object#a
   [f#2 t#1] c_call@../../../test.rb:12 Integer#times
    [f#3 t#1] b_call@../../../test.rb:12 Object#a
     [f#4 t#1] line@../../../test.rb:13 Object#a
     [f#4 t#1] line@../../../test.rb:14 Object#a
     [f#4 t#1] c_call@../../../test.rb:14 Kernel#raise
      [f#5 t#1] c_call@../../../test.rb:14 #exception
       [f#6 t#1] c_call@../../../test.rb:14 Exception#initialize
        [f#7 t#1] c_return@../../../test.rb:14 Exception#initialize
       [f#6 t#1] c_return@../../../test.rb:14 #exception
      [f#5 t#1] c_return@../../../test.rb:14 Kernel#raise
     [f#4 t#1] c_call@../../../test.rb:14 Exception#backtrace
      [f#5 t#1] c_return@../../../test.rb:14 Exception#backtrace
     [f#4 t#1] raise@../../../test.rb:14 Object#a
     [f#4 t#1] c_call@../../../test.rb:16 Module#===
      [f#5 t#1] c_return@../../../test.rb:16 Module#===
     [f#4 t#1] line@../../../test.rb:16 Object#a
     [f#4 t#1] b_return@../../../test.rb:16 Object#a
    [f#3 t#1] b_return@../../../test.rb:18 Object#a
   [f#2 t#1] c_return@../../../test.rb:12 Integer#times
  [f#1 t#1] return@../../../test.rb:19 Object#a
~~~

one can see that the return from 'a', which should be at f#2 is at f#1. The cause seems to be that when next/return/retry is called from within a rescue block, a b_return event is generated, which messes the stack count. No such event gets generated in "normal" control flows.

**Comment by doudou** [comment]
As I said, I wanted to put it here for the record, could not find any other bug related. It is fixed on ruby 2.1.6 and 2.2.2. 2.1.2 is affected (which, unfortunately, is also ubuntu 15.04's ruby version)

**Comment by deivid-rodriguez** [comment]
This is the bug you're looking for: https://github.com/deivid-rodriguez/byebug/issues/16 and this is the last remaining issue that should be fixed in ruby 2.3: https://github.com/deivid-rodriguez/byebug/issues/103

**Comment by doudou** [comment]
Damn ... just added to the background noise then :P

Thanks for byebug, by the way.

**Comment by deivid-rodriguez** [comment]
No problem, cheers!
