### ISSUE TITLE
Byebug(5.0.0) not stop in rspec (3.3.0)

### ISSUE THREAD

**Issue by ozeron** [deivid-rodriguez/byebug#157]
`byebug` don't stop execution while testing with `rspec`. In development mode everything works fine.
I'm using byebug (5.0.0) and rspec (3.3.0) and ruby 2.2.2

I also tried `pry-byebug`, and `binding.pry` it stops execution. But when I use `step`, `next`, `continue` or call any function it continue execution of program until next `binding.pry`

PS: I'm not using Rails.

spec_helper.rb
``` ruby
require 'rspec'
require 'rspec/collection_matchers'
require 'pry-byebug'

APP_ROOT = File.dirname __dir__
$: << APP_ROOT
$: << File.join(APP_ROOT, "lib")

DATA_PATH = File.join(APP_ROOT, 'spec', 'data')
require 'gps_receiver'

Dir[File.join(APP_ROOT, 'spec/support/**/**.rb')].each { |p| require(p) }
Utility::Logger.supress_logs!

RSpec.configure do |config|

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = false
  end

  config.order = :random
  Kernel.srand config.seed
end
```

**Comment by deivid-rodriguez** [comment]
@ozeron I'd need you to setup a repository or a failing test case so I can reproduce the problem. The information you gave is not enough. I'd also suggest that you remove `pry-byebug` and try to reproduce the problem using `byebug` only.

**Comment by ozeron** [comment]
@deivid-rodriguez here I created it for you. https://github.com/ozeron/rspec_test

**Comment by deivid-rodriguez** [comment]
@ozeron Thanks, what are the steps to reproduce?

**Comment by ozeron** [comment]
@deivid-rodriguez 
1). bundle
2). rspec

There are `byebug` instructions but interpretation not stop on them

**Comment by deivid-rodriguez** [comment]
First error I get

```
/home/davidr/code/rspec_test/lib/utility/logger.rb:1:in `require': cannot load such file -- log4r (LoadError)
```
because `log4r` is commented out in the Gemfile.

After readding it,

```
     Failure/Error: byebug
       #<File (class)> received :open with unexpected arguments
         expected: ("logfile/2015_04_13.bin", "ab")
              got: ("/home/davidr/.byebugrc")
        Please stub a default value first if message might be received with other args as well. 
```
Your test configuration disallows `byebug` from opening its configuration file. If I comment out the line

```
 allow(File).to receive(:open).with(path_to_log, 'ab')
```

`byebug` properly stops.

I don't think this is a problem in `byebug`.

**Comment by ozeron** [comment]
@deivid-rodriguez Oh, thank you, very much! :+1:

**Comment by deivid-rodriguez** [comment]
@ozeron You're welcome!
