### ISSUE TITLE
possible parser bug

### ISSUE THREAD

**Issue by CamJN** [deivid-rodriguez/byebug#159]
running `styles.all?{|s| s=='fill: #axis_grad;'}` in the byebug repl gives an error:
```
syntax error, unexpected end-of-input, expecting '}'
...s.all?{|s| s=='fill: #axis_grad
...                               ^
```

 because it interprets the `;` in the string as being part of the ruby code.

**Comment by deivid-rodriguez** [comment]
@CamJN This is expected behaviour. You can specify several `byebug` commands in a single line separating them with `;`. To evaluate actual code containing `;`, you have to escape the semicolon `\;`.
https://github.com/deivid-rodriguez/byebug/blob/master/GUIDE.md#command-syntax

**Comment by CamJN** [comment]
the semicolon is in a string it seems very weird to consider that normal behavior.

**Comment by deivid-rodriguez** [comment]
Yeah, we could probably do better, but `byebug` has other priorities now.

But if you don't want to escape semicolons, you can always work on fixing this yourself.
