### ISSUE TITLE
Confusing errors while installing byebug

### ISSUE THREAD

**Issue by Raw-G** [deivid-rodriguez/byebug#161]
I'm trying to set up my rails devevlopment environment on a Ubuntu 14.04. 

My Gemfile:
```
source 'https://rubygems.org'

gem 'rails',                '4.2.2'
gem 'sass-rails',           '5.0.2'
gem 'uglifier',             '2.5.3'
gem 'coffee-rails',         '4.1.0'
gem 'jquery-rails',         '4.0.3'
gem 'turbolinks',           '2.3.0'
gem 'jbuilder',             '2.2.3'
gem 'sdoc',                 '0.4.0', group: :doc

group :development, :test do
  gem 'sqlite3',     '1.3.9'
  gem 'byebug',      '3.4.0'
  gem 'web-console', '2.0.0.beta3'
  gem 'spring',      '1.1.3'
end
```

When I run bundle install, I get the following error:- 
```
    Installing byebug 3.4.0 with native extensions
    
    Gem::InstallError: byebug requires Ruby version >= 2.0.0.
    An error occurred while installing byebug (3.4.0), and Bundler
    cannot continue.
    Make sure that `gem install byebug -v '3.4.0'` succeeds before
    bundling.
```
But the odd thing is that I'm using ruby version 2.0.0p576 and I've tried this with ruby2.2.2 as well. Same error. I'm using rbenv.

What is even more confusing is that when I run 'gem install byebug -v '3.4.0' the installation succeeds, but when I run bundle install, it shows the same error that it cannot install byebug because of the ruby version issue. 

This is what I get when I run 'gem install -v '3.4.0' :
```
Fetching: debugger-linecache-1.2.0.gem (100%)
Successfully installed debugger-linecache-1.2.0
Fetching: slop-3.6.0.gem (100%)
Successfully installed slop-3.6.0
Fetching: byebug-3.4.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed byebug-3.4.0
3 gems installed
```

I'm not sure if this is a version incompatibility issue or if something else is wrong.

**Comment by os97673** [comment]
I'd guess that you are using different ruby version and to verify this I'd add `puts RUBY_VERSION` to the Gemfile.

**Comment by Raw-G** [comment]
It says 1.9.3!! That explains the error, but how do I fix it?

I mean when I type 'ruby -v' it says ruby2.0.0. And 'rbenv global' and 'rbenv local' both show ruby 2.0.0. 

Perhaps there is an asynchrony between rbenv and the ruby that bundle install uses? I'm new to this. Not sure where to look for help.

**Comment by os97673** [comment]
I'd ask on bundler's mailing list

**Comment by deivid-rodriguez** [comment]
@Raw-G What if you run `bundle exec ruby -v`. That should tell you the version `bundler` is using.
