### ISSUE TITLE
Lazy loading of Byebug

### ISSUE THREAD

**Issue by bquorning** [deivid-rodriguez/byebug#166]
I’m working on a project where we like to always have Byebug available in our test suite. But calling `require 'byebug'` in our spec helper adds 160ms to our RSpec startup time. And we want that number to be as low as possible.

Therefore, in our spec helper, I have defined this little hack:
```rb
def byebug
  require 'byebug'
  super
end
```

I’m wondering if we could implement something similar in Byebug itself, so I could just call something like `require 'byebug/lazy'` instead of the hack above?

**Comment by deivid-rodriguez** [comment]
Hi @bquorning. I understand your request. I have a macro in my editor myself that expands `debug` to `require 'byebug'; byebug`. :)

Perhaps we could even do this by default. `require 'byebug'` would just monkeypatch `Kernel` with the `byebug` method, and requiring the whole of `byebug` would be done inside the method.
