### ISSUE TITLE
Cursor invisible when byebug used inside minitest Progress reporter

### ISSUE THREAD

**Issue by JoeCohen** [deivid-rodriguez/byebug#170]
When I set a breakpoint in a rails app using `byebug` and run tests using [minitest-reporters](https://github.com/kern/minitest-reporters)' Progress reporter, 
then there is no cursor in byebug when the test hits a breakpoint.
In the Default reporter, the cursor behave properly.
(Rails 4.0.13, ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux], minitest 4.7.5, minitest-reporters 0.14.24).

I originally reported this as an issue for minitest-reporters.  The developer suggests: "byebug should be ready for situations when cursor is hidden by the program user debug and restore it." See [here](https://github.com/kern/minitest-reporters/issues/172). Makes sense to me as minitest does not know what the user might doing inside it.

(Sorry for merely creating an issue -- as opposed to trying to fix it -- but I have no idea how to fix the Progress reporter so this doesn't happen.)

**Comment by deivid-rodriguez** [comment]
Maybe related to #59 and #63? Thanks for the report.

**Comment by deivid-rodriguez** [comment]
@JoeCohen Can you reproduce this issue against latest master? If yes, could you provide me with a way of seeing it happening myself?

**Comment by JoeCohen** [comment]
David:
Thanks for following up, and sorry it took me so long to reply.
I have not seen this issue for a long time.  I forget when it disappeared.
I am currently using:

ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux], with the patch
you described in h
ttps://github.com/deivid-rodriguez/byebug/issues/189#issue-117556534
byebug 8.2.1
minitest (5.8.3),
minitest-reporters (1.1.7)

Regards,
-- Joe

**Comment by deivid-rodriguez** [comment]
Funny, I was hoping some unreleased commits would've fixed it... but since it's not happening anymore anyways I'll close. Please reopen if it reappears.

Salud!
