### ISSUE TITLE
require new feature, add debugger stub

### ISSUE THREAD

**Issue by windwiny** [deivid-rodriguez/byebug#172]
In windows OS, install a debug program, when c++ program raise exception then windows show a diagbox, has debug/terminal button, click debug can open debugger attach to the process. 

  Does byebug has similar function, when a ruby script raise exception, auto load byebug and breaked at the exception line, enable change some variable and canbe continue run other code ?

**Comment by deivid-rodriguez** [comment]
Hi. Yes, there's a post mortem mode to do just that. Enable it with `set post_mortem`.
