### ISSUE TITLE
Remote debugging is so slow

### ISSUE THREAD

**Issue by bcurtu** [deivid-rodriguez/byebug#174]
I run my RoR app using foreman with Puma as web server. When I activate remote degugging:
```ruby
  require 'byebug'
  Byebug.wait_connection = true
  Byebug.start_server('localhost', 33333)
```
The server slows down, it gets a request per second like if it was monothreading. Is this the expected behaviour? Can I improve the performance?

Thank you

**Comment by deivid-rodriguez** [comment]
There's already an opened issue to improve performance. Thanks.

**Comment by cben** [comment]
Sorry, I can't find any other open (or closed) issue about performance.
Can you give any pointers why it happens / what it would take to improve?

cc @borod108 who is experiencing this.

**Comment by cben** [comment]
Ping @deivid-rodriguez if you can shed any light/pointers on why it's slow, I'll _try_ to give this some love.
