### ISSUE TITLE
Setting to expand object by default like byebug 5.0.0

### ISSUE THREAD

**Issue by pratik60** [deivid-rodriguez/byebug#177]
In 6.0.0 and above
```
(byebug) User.first
#<User:0x007fcb4af328a8>
```

Before that 
```
(byebug) User.first
#<User id: 1, created_at: "2015-10-08 21:09:19", updated_at: "2015-10-08 21:09:19", name: "Test1"...>
```

Is there a setting, so that the default behaviour in this respect can go back to the before 6.0.0. I really much prefer it expanded object, as its easier for debugging.

**Comment by deivid-rodriguez** [comment]
Yes, the old one was better. I'll fix it.

**Comment by robacarp** [comment]
@deivid-rodriguez First off, thanks for your work with byebug. I know it's saved me many hours.

Is this by any chance related to [this change in the display of return values](http://stackoverflow.com/questions/32801920/format-byebugs-output)? I've also noticed that symbols don't print with their leading colon anymore either.

**Comment by deivid-rodriguez** [comment]
@robacarp Yes, it's the same issue.
