### ISSUE TITLE
control command not work

### ISSUE THREAD

**Issue by hgyxbll** [deivid-rodriguez/byebug#178]
at remote debug by open port 8990, I  send control command.(like kill\n)
I try to send kill or b file.rb:7, it do not respond and not have respond.
So which control commands are support?

**Comment by deivid-rodriguez** [comment]
@hgyxbll I need a sequence of commands I can run so I can reproduce the problem. Have a look a the [CONTRIBUTING](https://github.com/deivid-rodriguez/byebug/blob/master/CONTRIBUTING.md) file.

**Comment by hgyxbll** [comment]
I start the remote debug.
And start telnet use command:
telnet 127.0.0.1 8990

press below word: 
kill
and press enter, the debug do not stop

**Comment by deivid-rodriguez** [comment]
I need you to set up a sample repository where I can reproduce it. A list of commands I can copy/paste y my terminal to see what you're seeing.

Note that there are no tests for remote debugging support, and I don't use the feature myself. That's why I need a very easy clear reproduction.

**Comment by hgyxbll** [comment]
reproduce step:
1. create a file  debug.rb at /home/a, the content is:
 require 'byebug'
 Byebug.wait_connection = true;
 Byebug.start_server "127.0.0.1"
 byebug
2. create test.rb file, the content is:
puts "hello"
3.start debug, use the command: ruby -r/home/a/debug.rb test.rb
4.connect the debug by the command: telnet 127.0.0.1 8990
5.press "kill" and enter
6. the debug do not  stop, it do not handle the command

**Comment by deivid-rodriguez** [comment]
That's not how you debug remote programs. Have a look at the guide: https://github.com/deivid-rodriguez/byebug/blob/master/GUIDE.md#debugging-remote-programs

**Comment by hgyxbll** [comment]
sorry,  my description may be not right, the remote debug I mean is that: start debug and other program send command to control the debug.
this is used by a IDE which want to control the debug.
I ask this question because the sublime_debugger can not work now.
sublime_debugger will send control command but it do not work.
