### ISSUE TITLE
Cannot install byebug 6.0.2 on jruby-9.0.1.0

### ISSUE THREAD

**Issue by MonkeyOfRoll** [deivid-rodriguez/byebug#179]
Hi - I am new to ruby, so will do my best to explain this problem - hopefully this is the right place, though I understand that this could equally be a problem with bundler or something else in my setup. 

I am using 
bundler-1.10.6  
jruby-9.0.1.0

when attempting a bundle update, it tries to install byebug 6.0.2, but cannot due to jruby not supporting c extensions:

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

   /xxxxx/xxxxxxx/.rvm/rubies/jruby-9.0.1.0/bin/jruby -r ./siteconf20151030-50067-48g5im.rb extconf.rb
NotImplementedError: C extensions are not supported
    <top> at /xxxxx/xxxxxxx/rubies/jruby-9.0.1.0/lib/ruby/stdlib/mkmf.rb:1
  require at org/jruby/RubyKernel.java:939
   (root) at /xxxxx/xxxxxxx/.rvm/rubies/jruby-9.0.1.0/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
    <top> at extconf.rb:6

extconf failed, exit code 1

Gem files will remain installed in /xxxxx/xxxxxxx/.rvm/gems/jruby-9.0.1.0/gems/byebug-6.0.2 for inspection.
Results logged to /xxxxx/xxxxxxx/.rvm/gems/jruby-9.0.1.0/extensions/universal-java-1.7/2.2.0/byebug-6.0.2/gem_make.out
An error occurred while installing byebug (6.0.2), and Bundler cannot continue.
Make sure that `gem install byebug -v '6.0.2'` succeeds before bundling.

If you try gem install byebug -v '6.0.2' you get the same error - as expected. jruby does not support c extensions.

Is there a version of byebug that does not use c extensions?

**Comment by deivid-rodriguez** [comment]
Yeah, unfortunately `byebug` does not support `jruby`. :( #84
