### ISSUE TITLE
Build Error installing with Ruby 2.0.0-p576 and Rails 3.2.21 (and rbenv)

### ISSUE THREAD

**Issue by jackrg** [deivid-rodriguez/byebug#183]
When doing "bundle update rails", I get the error listed below. Works okay if I change my gemfile to read `"gem byebug, '~> 6.0'"`. Docs say that byebug 7.0 requires Ruby 2.0.0. Let me know if you need any more info.

Installing byebug 7.0.0 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/jackrg/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/byebug-7.0.0/ext/byebug
/Users/jackrg/.rbenv/versions/2.0.0-p576/bin/ruby -r ./siteconf20151105-95885-m351t9.rb extconf.rb
creating Makefile

current directory: /Users/jackrg/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/byebug-7.0.0/ext/byebug
make "DESTDIR=" clean

current directory: /Users/jackrg/.rbenv/versions/2.0.0-p576/lib/ruby/gems/2.0.0/gems/byebug-7.0.0/ext/byebug
make "DESTDIR="
compiling breakpoint.c
compiling byebug.c
byebug.c:339:9: error: implicit declaration of function 'rb_tracearg_event_flag' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if (rb_tracearg_event_flag(trace_arg) &
        ^
byebug.c:339:9: note: did you mean 'rb_tracearg_event'?
/Users/jackrg/.rbenv/versions/2.0.0-p576/include/ruby-2.0.0/ruby/debug.h:61:7: note: 'rb_tracearg_event' declared here
VALUE rb_tracearg_event(rb_trace_arg_t *trace_arg);
      ^
1 error generated.
make: *** [byebug.o] Error 1

make failed, exit code 2

**Comment by deivid-rodriguez** [comment]
My bad, `rb_tracearg_event_flag` was not public API in 2.0...

I'll fix this, but I'd strongly recommend you to upgrade your Ruby. The End Of Life of 2.0.0 is approaching and although `byebug` supports 2.0, it will behave weird in some cases. Given the high level of compatibility between ruby releases, I think the best one can do is upgrade.

**Comment by jackrg** [comment]
Oh, I will, I just upgraded from 1.93 last week, and I’m waiting a week before moving to the latest 2.x version (I also upgraded from Rails 3.1 then as well). 4 years of technical debt … ;)
