### ISSUE TITLE
Byebug.start_server Throws NoMethodError

### ISSUE THREAD

**Issue by PatrickHail** [deivid-rodriguez/byebug#195]
Trying to enable remote debugging by the steps outlined in this [guide](https://github.com/deivid-rodriguez/byebug/blob/master/GUIDE.md#debugging-remote-programs). I've added those lines to my config/initializers/development.rb and I get this exception when start the rails server:
`NoMethodError: undefined method 'start_server' for Byebug:Module`

```
byebug  8.2.0
ruby    2.2.2
rails   4.2.5
```

**Comment by deivid-rodriguez** [comment]
Can you try `require 'byebug/core'` instead of `require 'byebug'`? If that works, could you send a PR updating the Guide?
