### ISSUE TITLE
Can't launch irb in ruby-2.0.0-p647 because irb parses ARGV

### ISSUE THREAD

**Issue by josephks** [deivid-rodriguez/byebug#197]
When I try to invoke irb from within byebug inside my cucumber scenario I can't launch irb because irb tries to parse ARGV which contains cucumber's command line options.  This wasn't a problem for me in ruby 1.9.3 with debugger.

Modifying the execute method in lib/byebug/commands/irb.rb like this solves my problem:

```
    def execute
      unless processor.interface.is_a?(LocalInterface)
        return errmsg(pr('base.errors.only_local'))
      end
      saved_argv = ARGV.dup
      ARGV.clear
      IRB.start(__FILE__)
      ARGV.concat(saved_argv)
    end
```

**Comment by deivid-rodriguez** [comment]
Could you post some steps to reproduce this?

**Comment by josephks** [comment]
* Put `debugger` in your code
* Run `cucumber -b -r features`
* When you enter the debugger type `irb`
* Watch irb blow up because it can't partse "-b -r features'

**Comment by deivid-rodriguez** [comment]
Can you post a sample app? I don't want to deal with installing and setting up cucumber. You can also create a PR with a test case.

**Comment by deivid-rodriguez** [comment]
Thanks @josephks, I think you patch makes perfect sense. Could you create a PR?
