### ISSUE TITLE
NoMethodError (undefined method `step_out' for #<Byebug::Context:0x00000003c62f48>)

### ISSUE THREAD

**Issue by benams** [deivid-rodriguez/byebug#200]
I get this error everywhere I use 'byebug' in my controller. I couldn't find any information about this message, but it's very weird as I've used byebug successfully until now. 
After the error message I can see a very long and not informative trace which is related to active_record(?!), and then the server crashes and killed.
* I use rails 4.2.1 with byebug 8.2.1.

**Comment by deivid-rodriguez** [comment]
Hi @benams, sorry I forgot about this ticket. Are you still experiencing the problem? It looks like an installation problem...

**Comment by benams** [comment]
sorry but it was a long time ago, and I got a few more issues with the gem, so I replaced it with "pry"

**Comment by deivid-rodriguez** [comment]
Cool, closing then! Thanks @benams.
