### ISSUE TITLE
3 Tests failing on El Capitan Ruby 2

### ISSUE THREAD

**Issue by zagros** [deivid-rodriguez/byebug#203]
I'm getting this error when I run the rake tests after `bundle exec rake compile`.

No idea how to fix them:

     Finished in 3.365015s, 130.7572 runs/s, 147.1019 assertions/s.     
     
       1) Error:
     Byebug::NextWhenReturnInsideLoopInsideInitializeTest#test_next_works_return_inside_loop_inside_initialize:
     RuntimeError: Backtrace information is not available
         /Users/me/byebug/lib/byebug/frame.rb:20:in `frame_file'
         /Users/me/byebug/lib/byebug/frame.rb:20:in `file'
         /Users/me/byebug/test/support/matchers.rb:71:in `assert_location'
         /Users/me/byebug/test/commands/next_test.rb:89:in `block in test_next_works_return_inside_loop_inside_initialize'
         /Users/me/byebug/test/support/utils.rb:59:in `call'
         /Users/me/byebug/test/support/utils.rb:59:in `debug_code'
         /Users/me/byebug/test/commands/next_test.rb:89:in `test_next_works_return_inside_loop_inside_initialize'     
     
     
       2) Error:
     Byebug::NextAndDefineMethod#test_next_works_as_expected_with_define_method:
     RuntimeError: Backtrace information is not available
         /Users/me/byebug/lib/byebug/frame.rb:24:in `frame_line'
         /Users/me/byebug/lib/byebug/frame.rb:24:in `line'
         /Users/me/byebug/test/commands/next_test.rb:126:in `block in test_next_works_as_expected_with_define_method'
         /Users/me/byebug/test/support/utils.rb:59:in `call'
         /Users/me/byebug/test/support/utils.rb:59:in `debug_code'
         /Users/me/byebug/test/commands/next_test.rb:126:in `test_next_works_as_expected_with_define_method'     
     
     
       3) Failure:
     Byebug::FinishBeforeReturn#test_finish_0_stops_right_before_frame_returns__convoluted_case [/Users/me/byebug/test/commands/finish_test.rb:138]:
     --- expected
     +++ actual
     @@ -1 +1 @@
     -14
     +11     
     
     
     440 runs, 495 assertions, 1 failures, 2 errors, 2 skips     
     
     You have skipped tests. Run with --verbose for details.
     mm:byebug me$ ruby -v
     ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]

**Comment by deivid-rodriguez** [comment]
Yes, this is expected. We can say Ruby 2 is now only partially supported.

**Comment by deivid-rodriguez** [comment]
When I say Ruby 2, I mean Ruby `2.0`. Ruby `2.1`, `2.2` and `2.3` should work just fine.
