### ISSUE TITLE
Disable .byebug_history

### ISSUE THREAD

**Issue by josephan** [deivid-rodriguez/byebug#204]
Is there a way to disable .byebug_history? Currently I added it to the .gitignore and if there is a way to change it, I can help by adding it to the markdown doc.
Thank you! :wave: :beetle:

**Comment by deivid-rodriguez** [comment]
Hi @josephan, sorry for taking time to reply.

I think the `.gitignore` file is a good place for `.byebug_history`. However, if for some reason you don't want it generated at all, you can use `set noautosave`. Notice though that If you don't save history to `.byebug_history`, you won't get permanent history (across `byebug` runs) in your `byebug` prompt.

Also, if you want to disable permanently saving `.byebug_history`, you can put `set noautosave` in your `.byebugrc` file. I actually found that this was not actually working as expected, so I fixed it in version `8.2.2`.

Regards!

**Comment by josephan** [comment]
Thank you!
