### ISSUE TITLE
Pry-style syntax coloring?

### ISSUE THREAD

**Issue by QasimQureshi** [deivid-rodriguez/byebug#205]
I really like Byebug, I've been trying to see if there's an option to get pry-style syntax coloring. Are there any plans to add this?

![image](https://cloud.githubusercontent.com/assets/3591082/12700700/65ac12f4-c80f-11e5-8235-4924c2be8bef.png)

**Comment by deivid-rodriguez** [comment]
Hi! This [was requested](https://github.com/deivid-rodriguez/byebug/issues/23) a long time ago. I'd like to have it in `byebug` but nobody has stepped in and fixed it.

**Comment by ingolfured** [comment]
Why is this closed? Would be a great feature, any ideas where to start?

**Comment by deivid-rodriguez** [comment]
Read my last comment, the answer is in front of you.
