### ISSUE TITLE
 uninitialized constant Byebug::Interface::Setting

### ISSUE THREAD

**Issue by sriedel** [deivid-rodriguez/byebug#209]
I am currently encountering this when placing a byebug instruction within my specs. I've tried requiring byebug with a -rbyebug command line option of rspec (3.4.2) and at the top of my spec_helper. Both don't work. 

It could be due to my having to use fakefs extensively within my tests, so if Interface::Setting is a conditional or late requirement, it may well be that the class simply cannot be found.

I'm using byebug 8.2.2 under ruby 2.3.0.

The relevant part of the stack trace is:

     # /home/sr/.rvm/gems/ruby-2.3.0/gems/byebug-8.2.2/lib/byebug/interface.rb:106:in `autosave'
     # /home/sr/.rvm/gems/ruby-2.3.0/gems/byebug-8.2.2/lib/byebug/processors/command_processor.rb:136:in `after_repl'
     # /home/sr/.rvm/gems/ruby-2.3.0/gems/byebug-8.2.2/lib/byebug/processors/command_processor.rb:100:in `ensure in process_commands'
     # /home/sr/.rvm/gems/ruby-2.3.0/gems/byebug-8.2.2/lib/byebug/processors/command_processor.rb:100:in `process_commands'
     # /home/sr/.rvm/gems/ruby-2.3.0/gems/byebug-8.2.2/lib/byebug/processors/command_processor.rb:56:in `at_line'
     # /home/sr/.rvm/gems/ruby-2.3.0/gems/byebug-8.2.2/lib/byebug/context.rb:96:in `at_line'

**Comment by sriedel** [comment]
Adding an explicit "require 'byebug/setting'" to lib/byebug/core.rb gets me past this error, but results in different errors down the line:
lib/byebug/setting.rb:45 assumes that there is always a setting associated with the queried key; for some reason this is not the case for me. Adding a nil-safety catch results here results in a further error that states that /home/sr/.rvm/gems/ruby-2.3.0/gems/byebug-8.2.2/lib/byebug/printers/texts/plain.yml cannot be found.
I didn't follow the rabbit hole any further.

It looks like byebug has problems with a fakefs environment at the moment.

**Comment by deivid-rodriguez** [comment]
Two bad... It'd be great if you could keep digging!

**Comment by deivid-rodriguez** [comment]
Since the original error is fixed I'm going to close it. Please open another ticket with the subsequent error if you still interested in getting it fixed.
