### ISSUE TITLE
byebug 8.2.1 can't `continue`

### ISSUE THREAD

**Issue by jrochkind** [deivid-rodriguez/byebug#212]
I frequently use byebug inside of rspec. byebug 8.2.1, ruby 2.2.0p0

Trying to exit my session and "continue" almost always results in a segfault. 

This is something that used to happen to me on old versions of byebug, it seems to be back. 

Is this a known problem? I can try to make a smallest possible reproducible example, but it's of course a pain, I thought I'd check first.

**Comment by deivid-rodriguez** [comment]
Check out the README and use one of the recommended Ruby versions. The one you're using is too old. Regards.

**Comment by jrochkind** [comment]
thank you!

**Comment by deivid-rodriguez** [comment]
No problem! :wink:
