### ISSUE TITLE
Support debugging C extensions

### ISSUE THREAD

**Issue by v0dro** [deivid-rodriguez/byebug#215]
I'm from [SciRuby](www.github.com/sciruby/) and we use C extensions extensively in our gems.

A huge problem is debugging C extensions. It's very very difficult to have a reliable set of procedures which we can fall onto for debugging C-level errors like seg faults and memory leaks.

byebug being able to do that would be great.

**Comment by deivid-rodriguez** [comment]
@v0dro Not sure what you mean... You mean like making `byebug` able to debug C code? That's definitely not an option.

**Comment by v0dro** [comment]
No I mean at least being able to see a C-level stack trace in case there is something wrong with a C extension. So the Ruby function calls can be interleaved with the respective C function calls.

**Comment by deivid-rodriguez** [comment]
I think you do get a stacktrace if you get a segfault. Not very specific, but gets better if you compile the extension with debugging symbols enabled. For example, in `byebug` you get that by compiling with the `DEBUG` env variable set to true.

**Comment by v0dro** [comment]
Yea I do but it won't point the exact line at which the segfault occured the way gdb does. Will that be possible through byebug?

**Comment by deivid-rodriguez** [comment]
That's what compiling with debugging symbols provides.

**Comment by deivid-rodriguez** [comment]
But has nothing to do with `byebug` but with the way you compile the specific extension.

**Comment by v0dro** [comment]
Will give it a shot. Closing this now.

**Comment by deivid-rodriguez** [comment]
:+1: Good luck!
