### ISSUE TITLE
's' does not mean 'step' as the documentation says

### ISSUE THREAD

**Issue by hlindberg** [deivid-rodriguez/byebug#216]
The documentations shows 's[tep]' for step, but typing just an 's' does something else (beginning with 's').

This is driving me nuts. Typing 'step' each time is a pain. The shortest I could come up with was 's 1'.

**Comment by hlindberg** [comment]
I found that it is possible to type just return to repeat a 'step', that makes it somewhat easier. Would still like to see 's' being supported as you often shift between 'next' and 'step'.

**Comment by deivid-rodriguez** [comment]
Don't know wha't going on here. Do you have a local variable called `s`. If not, `s` should work.

Please, reopen if you can provide me with a way te reproduce this problem.

**Comment by hlindberg** [comment]
I was surprised when debugging complex code that I did not end up where I expected using 's'. On the next round I used 'step' and it worked. There was no 's' variable. I tried recreating this with a simple sample, but no luck. I have moved on from the problem in particular but will come back if I see that behavior again.

**Comment by deivid-rodriguez** [comment]
Fair enough. Make sure you use Ruby 2.1 for your tests!

**Comment by hlindberg** [comment]
Are later rubies than 2.1 ok? I am using 2.2.4 as the default right now.

**Comment by deivid-rodriguez** [comment]
Yes, yes. Sorry. I meant rubies greater than or equal to `2.1`.
