### ISSUE TITLE
Support for Pretty Printing

### ISSUE THREAD

**Issue by hlindberg** [deivid-rodriguez/byebug#222]
(oh, no, he is back with more printing stuff :-) )

I often end up debugging exceptions (that are swallowed, or rewritten, and I want to examine the backtrace of the exception). What I used to do on the old debugger was to use the `pp` command. 
That does not seem to be directly supported in byebug.
```
pp exception.backtrace
(byebug) pp exception.backtrace
*** NoMethodError Exception: undefined method `pp' for Puppet:Module

(byebug) pp(exception.backtrace)
*** NoMethodError Exception: undefined method `pp' for Puppet:Module
```
 In order to make that work, I had to:
```
require 'pp'
PP.pp(e.backtrace)
```
Which is a bit clunky. Would very much like to see support for `pp` unless there is some other convenient way of displaying that backtrace in a readable way. (e.g. if the `bt` command could accept an exception as an argument). Although `pp` in general is handy.

(Have not tried requiring 'pp' early)

**Comment by deivid-rodriguez** [comment]
@hlindberg Thanks for reporting this and sorry for getting to it late.

I decided that I don't want to mantain something like this inside `byebug`, so I'll close.

Regards!
