### ISSUE TITLE
.byebugrc not read at startup

### ISSUE THREAD

**Issue by sethk** [deivid-rodriguez/byebug#223]
From reading the documentation, this should be the default behavior, right? Invoking with ``--rc`` causes the file to be sourced, but failed commands are ignored without any diagnostic output.

**Comment by deivid-rodriguez** [comment]
Yes, it should be the default behavior. If it's not, could you give me a way to reproduce the problem? It's certainly read in simple cases.

Regarding the diagnostic output, yep. That's something to be improved!

**Comment by sethk** [comment]
Okay, well that now reads my rc file, but that exposes the next layer of problems. Shall I create another bug for the missing diagnostic output? My feeling is that all I/O with the user should be via ``IO.console`` AKA ``/dev/tty``.

**Comment by deivid-rodriguez** [comment]
So this PR is to be merged, right? Or should we investigate the next layer of problems first?

Yes, please, another bug for improving diagnosis output. Also, can you help with migrating everything to `IO.console`?

**Comment by sethk** [comment]
Yes, let's merge this and I'll either file another bug or PR. =)
