### ISSUE TITLE
Won't install under Ruby 2.3.0

### ISSUE THREAD

**Issue by RedFred7** [deivid-rodriguez/byebug#227]
Not sure if this is related to #165 but when I `gem install byebug -v '8.2.2'` I get the following:

> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
> 
>     current directory: /home/fred/.rvm/gems/ruby-2.3.0@cuba_genie/gems/byebug-8.2.2/ext/byebug
> /home/fred/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20160325-18907-cff2tg.rb extconf.rb
> creating Makefile
> 
> current directory: /home/fred/.rvm/gems/ruby-2.3.0@cuba_genie/gems/byebug-8.2.2/ext/byebug
> make "DESTDIR=" clean
> 
> current directory: /home/fred/.rvm/gems/ruby-2.3.0@cuba_genie/gems/byebug-8.2.2/ext/byebug
> make "DESTDIR="
> compiling locker.c
> compiling context.c
> compiling byebug.c
> compiling threads.c
> compiling breakpoint.c
> linking shared-object byebug/byebug.so
> /usr/bin/ld: cannot find -lgmp
> collect2: error: ld returned 1 exit status
> make: *** [byebug.so] Error 1
> 
> make failed, exit code 2

If I switch over to Ruby 2.2.1 (I use RVM) the gem installs without any problems

**Comment by deivid-rodriguez** [comment]
No, I don't think so... It seems like a problem with your ruby 2.3.0 installation or even a bug in ruby. Try installing another gem with C extensions, `nokogiri` for example. Does it fail too?

**Comment by RedFred7** [comment]
Yes, nokogiri fails too. Again, no problems under 2.2.1. You're right, it must be my installation or that specific ruby build. In any case, I'll close this down, thanks.

**Comment by deivid-rodriguez** [comment]
No problem.
