### ISSUE TITLE
Byebug loses Keyboard input on windows

### ISSUE THREAD

**Issue by Startouf** [deivid-rodriguez/byebug#237]
* byebug version 8.2.4, using it with Rails 5.0.0beta3
* Windows 10, ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]

Something quite weird happens randomly when I am using byebug. Sometimes I partially lose keyboard input. Partially because 

* up/down arrows for reverse history still work and pop up the text in my powershell windows
* Enter key still "submits" the input, 
* any other key, including paste shortcut, does not do anything (apart from submitting the prevous command when I press enter)

I cannot even kill the process with Ctrl+c and I have to manually close my PS window and restart my ruby/rails process when that happens

I have no idea how I can debug that and give you feedback. Please tell me if there is something I can do, or I will keep monitoring and reply asap when I can find easily reproduceable steps

**Comment by deivid-rodriguez** [comment]
This is a dup of #59 or #63, we should probably merge those into a single bug! You could try reapplying https://github.com/deivid-rodriguez/byebug/commit/bb98cd60cfeceee8ce626a222346ef432e7d2a0e and see if it fixes the issue.
