### ISSUE TITLE
rspec with byebug

### ISSUE THREAD

**Issue by Shwetakale** [deivid-rodriguez/byebug#252]
I am using byebug in rspec example. My current test case is failing but when I use byebug after exiting it always shows as its passing.

I haven't debuged it so much but Is this bug related to byebug or rspec?

**Comment by deivid-rodriguez** [comment]
Hei @Shwetakale , unfortunately I can't really answer unless you elaborate a bit more. Maybe you can try to isolate the example and share it?

**Comment by Shwetakale** [comment]
@deivid-rodriguez Sorry for late reply. [Here](https://github.com/Shwetakale/byebug_issue_252_ex/blob/master/spec/model/user_spec.rb) is example which reproduces above issue.

Ideally, test case ```"checks if 1 equal to 2"```  should fail and it behaves the same but when I add ```byebug``` in that test case and exists it shows ```0 Failures```

I am just using following snippet of code

    it "checks if 1 equal to 2" do
      byebug
      expect(1).to eq 2
    end

Am I doing something wrong?
