### ISSUE TITLE
Feature request: Skip over code that is not mine

### ISSUE THREAD

**Issue by danlo** [deivid-rodriguez/byebug#257]
Greetings,

I use https://github.com/collectiveidea/interactor a lot and what bugs me a lot is that often, when doing "n" for next, I get dragged trough interactor's code a lot when I don't need to be seeing it.

I wish I could have a .byebug or  skip_over command to 

skip_over /usr/local/lib/ruby/gems/2.2.0/gems/interactor-3.1.0/lib/interactor.rb

or

skip_over /usr/local/lib/ruby/gems/*

So that, "n", would just by pass all such files, until it gets back to my code!

Thank you for this wonderful too!

-daniel

**Comment by deivid-rodriguez** [comment]
Dup of #47, thanks for your request!
