### ISSUE TITLE
Question: does byebug have api to break execution in an external ruby program

### ISSUE THREAD

**Issue by gideondsouza** [deivid-rodriguez/byebug#276]
Sorry if this is annoying, I didn't see any docs, I'm an experienced dev but ruby-newbie. 

I want to just toy around and develop some rudimentary front end for debugging ruby. I was wondering whether byebug could be used as a library. Where if I have a `target.rb` file I can use byebug to debug this file? But I have to insert byebug statements in there, is there a way to break a certain line without doing this?

**Comment by zetetic** [comment]
> I didn't see any docs

https://github.com/deivid-rodriguez/byebug/blob/master/GUIDE.md

I don't think theses issues are appropriate for a Q&A. Maybe you could try asking this on StackOverflow. It would help to have a specific example of what you are trying to accomplish.
