### ISSUE TITLE
"Sorry, you can't use byebug without Readline"

### ISSUE THREAD

**Issue by olivierlacan** [deivid-rodriguez/byebug#289]
I started encountering this issue inside a Rails app with byebug 9.0.5 and Ruby 2.2.5. Didn't change either Rails or Ruby after installing byebug. One day it worked fine, the next I couldn't boot the Rails app due to this issue. I'm really curious if there's any other solution than reinstalling that Ruby version. 

```
    Sorry, you can't use byebug without Readline. To solve this, you need to
    rebuild Ruby with Readline support. If using Ubuntu, try `sudo apt-get
    install libreadline-dev` and then reinstall your Ruby.
/Users/olivierlacan/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require': dlopen(/Users/olivierlacan/.rbenv/versions/2.2.5/lib/ruby/2.2.0/x86_64-darwin15/readline.bundle, 9): Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib (LoadError)
  Referenced from: /Users/olivierlacan/.rbenv/versions/2.2.5/lib/ruby/2.2.0/x86_64-darwin15/readline.bundle
  Reason: image not found - /Users/olivierlacan/.rbenv/versions/2.2.5/lib/ruby/2.2.0/x86_64-darwin15/readline.bundle
```

It's honestly a little odd, I don't remember needing to do anything special with Rubies on prior versions of byebug so I'm thinking this might be less straightforward than it appears perhaps. In any case this issue should help others since I couldn't find any exact matches on Google for this exact error message.

**Comment by olivierlacan** [comment]
Apparently this could be due to Homebrew: 
- https://twitter.com/chattsm/status/783269018828439552
- https://twitter.com/chattsm/status/783269380247392256

> @olivierlacan I had this issue on Friday after bumping a bunch of Homebrew libs. Had to recompile Ruby to fix!

> @olivierlacan one of these will be the offender - `brew uses --installed readline`

For me this was the output:
```
$ brew uses --installed readline
augeas                               bash                                 postgresql                           python                               sqlite
```

**Comment by chattsm** [comment]
Hi @olivierlacan, what is your output from `brew info readline`?

Mine is... 
```
$ brew info readline
readline: stable 7.0 (bottled) [keg-only]
Library for command-line editing
https://tiswww.case.edu/php/chet/readline/rltop.html
/usr/local/Cellar/readline/7.0 (45 files, 2M)
  Poured from bottle on 2016-09-30 at 11:07:04
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/readline.rb
```
My Ruby (managed by `ruby-install` / `chruby`) broke after `2016-09-30 at 11:07:04`, which is when I updated a bunch of my Homebrew installs and ran a `brew cleanup` (thus removing readline v6.0).

```
$ ls -l /usr/local/opt/readline/lib
total 2744
-r--r--r--  1 chattsm  admin   84728 30 Sep 11:07 libhistory.7.0.dylib
lrwxr-xr-x  1 chattsm  admin      20  7 Sep 22:16 libhistory.7.dylib -> libhistory.7.0.dylib
-r--r--r--  1 chattsm  admin   84480  7 Sep 22:16 libhistory.a
lrwxr-xr-x  1 chattsm  admin      20  7 Sep 22:16 libhistory.dylib -> libhistory.7.0.dylib
-r--r--r--  1 chattsm  admin  459608 30 Sep 11:07 libreadline.7.0.dylib
lrwxr-xr-x  1 chattsm  admin      21  7 Sep 22:16 libreadline.7.dylib -> libreadline.7.0.dylib
-r--r--r--  1 chattsm  admin  751528  7 Sep 22:16 libreadline.a
lrwxr-xr-x  1 chattsm  admin      21  7 Sep 22:16 libreadline.dylib -> libreadline.7.0.dylib
```
I had to re-compile Ruby to fix this issue. Interesting to know if there is a better/simpler fix for it!

**Comment by olivierlacan** [comment]
Someone also suggested adding `rb-readline` as a development group dependency in the Gemfile: https://twitter.com/ndrx42/status/783288843906801664

**Comment by olivierlacan** [comment]
@chattsm 

```
$ brew info readline
readline: stable 7.0 (bottled) [keg-only]
Library for command-line editing
https://tiswww.case.edu/php/chet/readline/rltop.html
/usr/local/Cellar/readline/6.3.8 (46 files, 2.0M)
  Poured from bottle on 2015-09-11 at 16:22:41
/usr/local/Cellar/readline/7.0 (45 files, 2M)
  Poured from bottle on 2016-10-03 at 18:43:51
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/readline.rb
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.


Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include
```

**Comment by olivierlacan** [comment]
Looks like this is related to #118 and could actually be a dupe, please close if that's the case. It seems like recommending `rb-readline` as a development dependency tends to [lead to issues](https://github.com/deivid-rodriguez/byebug/issues/118#issuecomment-138492675).

**Comment by deivid-rodriguez** [comment]
@olivierlacan Did you try reinstalling your Ruby. I'm not aware of a better solution...

By the way, anyone contributing to the discussion here, feel free to improve the troubleshooting instructions for OSX. I don't use that, so I have no idea. Or maybe a wiki page should be created and linked from the error message, I don't know.

**Comment by kntmrkm** [comment]
I had reinstalled ruby. It have been works well.

**Comment by deivid-rodriguez** [comment]
I'm going to close this since it does not seem like a problem in byebug.

**Comment by mehta** [comment]
To fix this, run following command in your shell -  

`ln -s  /usr/local/opt/readline/lib/libreadline.dylib  /usr/local/opt/readline/lib/libreadline.6.dylib`

**Comment by kirillweb** [comment]
@mehta thanks!

**Comment by parquar** [comment]
@mehta bloody perfect!

**Comment by hraynaud** [comment]
@mehta solution worked for me too.

**Comment by jasonfagan** [comment]
@mehta definite fix for Sierra, no reinstall or recompile of Ruby needed. Thanks a lot for this tip!!

**Comment by iqbalhasnan** [comment]
Thanks @mehta

**Comment by dimosz** [comment]
@mehta worked for me, thanks.

**Comment by Schwad** [comment]
@olivierlacan 's post worked for me, thanks so much!

```
Someone also suggested adding rb-readline as a development group dependency in the Gemfile: https://twitter.com/ndrx42/status/783288843906801664
```

Also on a side note, loving Ruby Facets man!

**Comment by wflanagan** [comment]
Worked for me in El Capitan as well.

**Comment by bhoormeena** [comment]
@mehta   thanks buddy!

**Comment by milan-mitra** [comment]
@mehta 👍

**Comment by pinkopaque22** [comment]
Thanks man! That did the trick. SO grateful.

**Comment by ragavendra** [comment]
@mehta  answer worked for me too, but had to do a bit change on Linux like below.

`sudo ln -s /usr/lib/libreadline.so /usr/lib/libreadline.so.6`

**Comment by danmoore2205** [comment]
thanks @mehta saved me!

**Comment by soultech67** [comment]
I was using the `gem 'rb-readline'` workaround but it stopped working for me yesterday. After some googling I found that a solution is to rebuild ruby on os/x, this way it's built on the latest libs / header files.  This worked for me and seems more like a solution than a work-around.  

I wrote up a gist here to give solutions for `rvm` and `rbenv` users: https://gist.github.com/soultech67/33ba09706e091c06ce66684cd28015ac

**Comment by neohunter** [comment]
Worked also on el capitan.

**Comment by robinhorios** [comment]
@mehta :shipit:

**Comment by duinness** [comment]
@mehta's solution worked for me on Yosemite

**Comment by Iqlaas** [comment]
@mehta still works mate. cheers.

**Comment by txssseal** [comment]
@mehta gracias senor

**Comment by baird** [comment]
@mehta my dude

**Comment by tarlig** [comment]
@mehta Dankeschoen! Excellent!

**Comment by bf4** [comment]
Apologies for commenting on an old thread, but if you're on homebrew, the simplest command is something like `brew switch readline 6.3.8`

**Comment by wayne-crs** [comment]
@mehta Cheers. Worked for me on High Sierra

**Comment by yogeshmurugesan** [comment]
@mehta worked for me.

**Comment by baurine** [comment]
@bf4 's solution works for me.

I met this problem after homebrew upgrading the readline from 7.0.5 to 8.0.

```
> ls -alh /usr/local/opt/readline/lib
total 1448
drwxr-xr-x  11 sparkhuang  staff   352B Dec 20 05:07 .
drwxr-xr-x  12 sparkhuang  staff   384B Jan 17 15:27 ..
-r--r--r--   1 sparkhuang  staff    39K Jan 17 15:27 libhistory.8.0.dylib
lrwxr-xr-x   1 sparkhuang  staff    20B Dec 20 05:07 libhistory.8.dylib -> libhistory.8.0.dylib
-r--r--r--   1 sparkhuang  staff    45K Dec 20 05:07 libhistory.a
lrwxr-xr-x   1 sparkhuang  staff    20B Dec 20 05:07 libhistory.dylib -> libhistory.8.0.dylib
-rw-r--r--   1 sparkhuang  staff   234K Jan 17 15:27 libreadline.8.0.dylib
lrwxr-xr-x   1 sparkhuang  staff    21B Dec 20 05:07 libreadline.8.dylib -> libreadline.8.0.dylib
-r--r--r--   1 sparkhuang  staff   397K Dec 20 05:07 libreadline.a
lrwxr-xr-x   1 sparkhuang  staff    21B Dec 20 05:07 libreadline.dylib -> libreadline.8.0.dylib

> ls -alh /usr/local/Cellar/readline
total 0
drwxr-xr-x   5 sparkhuang  staff   160B Jan 17 15:27 .
drwxrwxr-x  75 sparkhuang  admin   2.3K Jan 17 15:35 ..
drwxr-xr-x  12 sparkhuang  admin   384B Jan 25  2018 7.0.3_1
drwxr-xr-x  12 sparkhuang  staff   384B Sep  6 16:41 7.0.5
drwxr-xr-x  12 sparkhuang  staff   384B Jan 17 15:27 8.0.0
```

I use `brew switch readline 7.0.5` to revert it back and it works back.

```
> brew switch readline 7.0.5
Cleaning /usr/local/Cellar/readline/8.0.0
Cleaning /usr/local/Cellar/readline/7.0.5
Cleaning /usr/local/Cellar/readline/7.0.3_1
Opt link created for /usr/local/Cellar/readline/7.0.5
```

**Comment by LarryWachira** [comment]
If you use [rvm](https://rvm.io/) you can equally run `rvm reinstall` to resolve the readline mismatch.

**Comment by skbailey** [comment]
@mehta the real MVP, this worked for me

**Comment by itcentralstation** [comment]
Same problem as @baurine in that some library is looking for libreadline.7.dylib even after I upgraded to readline 8. So I used

`cd /usr/local/opt/readline/lib`
`ln -s libreadline.dylib libreadline.7.dylib`

I'm not proud but it works.

**Comment by davidcpell** [comment]
same as @coisnepe - had to use:

```
$ ln -s /usr/local/opt/readline/lib/libreadline.dylib /usr/local/opt/readline/lib/libreadline.7.dylib
```

**Comment by srikirancse** [comment]
@mehta Man of the hour!

**Comment by storrence88** [comment]
@itcentralstation This worked for me! Thanks!

**Comment by jamsi** [comment]
@davidcpell thanks mate, worked well :D

**Comment by masak2009** [comment]
@mehta - This solution is absolutely right. All you need is locate **libreadline.dylib** in your macOS system (I am using macports). Probably libreadline.dylib is symlink to another libreadline library. In my case it is libreadline.8.0.dylib. So in same dir where is this file create symlink:
`ln -s libreadline.8.0.dylib libreadline.6.dylib`

Now byebug starts to work

**Comment by sarsena** [comment]
Thank you! I just needed to change the symlink to point to `7` instead but it worked after.  `ln -s libreadline.8.0.dylib libreadline.7.dylib`

**Comment by mothule** [comment]
I changed the version with `brew switch` and solved it, because it's on Mac.

like it `$ brew switch readline 7.0.3_1`.

**Comment by masak2009** [comment]
@mothule - On mac you should use brew or macports. The key is in "missing file" or "missing link" which solve at general the problem.

**Comment by donald-s** [comment]
I ran into this issue today and it appears that the problem for me was that a recent update for XCode failed. Reinstalling a fresh version of XCode and then reinstalling the Ruby version worked for me.

**Comment by stdedos** [comment]
_Originally posted by @Schwad in https://github.com/deivid-rodriguez/byebug/issues/289#issuecomment-271143779_
> @olivierlacan 's post worked for me, thanks so much!
> 
> ```
> Someone also suggested adding rb-readline as a development group dependency in the Gemfile: https://twitter.com/ndrx42/status/783288843906801664
> ```
> 
> Also on a side note, loving Ruby Facets man!

Would it make sense to add it as a dependency of `byebug` @deivid-rodriguez?

**Comment by deivid-rodriguez** [comment]
We tried that for a while but that caused problems for non windows users. I'll try to migrate to use the brand new pury ruby readline implementation that ruby 2.7 will use by default: [reline](https://github.com/ruby/reline).

**Comment by lavaldi** [comment]
hey @donald-s how did you reinstall XCode and Ruby?

**Comment by Oceantidote** [comment]
@mehta you legend 🙏

**Comment by MFRWDesign** [comment]
On OSX:
```
brew list readline
```
Then look for the installed version of readline's libreadline.X.X.dylib library. For illustration through example, this is what I saw:
```
○ → brew list readline
/usr/local/Cellar/readline/8.0.4/include/readline/ (8 files)
/usr/local/Cellar/readline/8.0.4/lib/libhistory.8.0.dylib
/usr/local/Cellar/readline/8.0.4/lib/libreadline.8.0.dylib
/usr/local/Cellar/readline/8.0.4/lib/pkgconfig/readline.pc
/usr/local/Cellar/readline/8.0.4/lib/ (6 other files)
/usr/local/Cellar/readline/8.0.4/share/doc/ (3 files)
/usr/local/Cellar/readline/8.0.4/share/info/ (3 files)
/usr/local/Cellar/readline/8.0.4/share/man/ (2 files)
/usr/local/Cellar/readline/8.0.4/share/readline/ (16 files)
```

Then just `cd` into the appropriate directory, here it would be:
```
cd /usr/local/Cellar/readline/8.0.4/lib/
```

And then you can create the symlink you need for your missing library. For me, that the original error was `Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib`, so I ran this command:
```
ln -s libreadline.8.0.dylib libreadline.7.dylib
```

And like magic - it's fixed!! Thank you @mehta !!!
