### ISSUE TITLE
Error building byebug with clang

### ISSUE THREAD

**Issue by slacka** [deivid-rodriguez/byebug#292]
Trying to build primus with clang results in:

`ruby.h:933:1: error: attribute 'deprecated' is ignored, place it after "struct" to apply attribute to type declaration`

The full log of this error can be found here:
http://clang.debian.net/logs/2016-08-30/ruby-byebug_5.0.0-1_unstable_clang.log

**Comment by deivid-rodriguez** [comment]
@slacka Which version are you trying to build? `5.0.0` is very old.

**Comment by slacka** [comment]
The version that comes with Ubuntu. Yes, it's 5.0.
https://launchpad.net/ubuntu/+source/ruby-byebug

Has this bug been fixed? You might want to talk to the Debain maintainer(Ubuntu upstream).
https://packages.debian.org/sid/ruby/ruby-byebug

**Comment by deivid-rodriguez** [comment]
> Has this bug been fixed?

I don't know.

> You might want to talk to the Debain maintainer(Ubuntu upstream). https://packages.debian.org/sid/ruby/ruby-byebug.

I will, thanks.

**Comment by deivid-rodriguez** [comment]
I contacted debian mantainer but got no answer. However, the upgrade seems planned: https://tracker.debian.org/pkg/ruby-byebug.

So I'll close this.
