### ISSUE TITLE
Ability to show more surrounding code

### ISSUE THREAD

**Issue by garmoshka-mo** [deivid-rodriguez/byebug#295]
By default byebug shows 10 lines, e.g. lines `[40, 49]`
It would be great option to see some more surrounding code (with command like `expand` or similar name), for example lines 30-60

**Comment by deivid-rodriguez** [comment]
You're looking at the `listsize` setting. For example,

```
set listsize 20
```

to change the default 10 to 20. Drop that line in your `.byebugrc` file if you want to change it permanently.

**Comment by garmoshka-mo** [comment]
Also discovered, that `l 30-60` solves my problem.
Question wouldn't appear if [ReadMe](https://github.com/deivid-rodriguez/byebug) would contain description of `list` command. E.g. "Show surrounding code around execution command"
Do you wish me to create pull request?

**Comment by deivid-rodriguez** [comment]
That information is in the manual: https://github.com/deivid-rodriguez/byebug/blob/master/GUIDE.md#examining-program-source-files-list.

I think it belongs there, but we could definitely use a Table of Contents in the README linking to each section in the manual. Would you like to take care of that?

**Comment by garmoshka-mo** [comment]
Yes, please check if it looks convenient: https://github.com/deivid-rodriguez/byebug/pull/296
