### ISSUE TITLE
Slow debugger in remote mode

### ISSUE THREAD

**Issue by jeffutter** [deivid-rodriguez/byebug#302]
## Problem description

It seems that Byebug.start_server at the top of my (sinatra) application causes near 30x performance regressions in some cases.

A certain query which fires off a bunch of DataMapper queries and returns a ton of JSON executes approximately 30x slower when a byebug server is started (with no clients connected)

## Expected behavior

I would expect no performance penalty, particularly if no client is connected.

## Actual behavior

The given endpoint benchmarks (with wrk) 30x slower.

## Steps to reproduce the problem

Unfortunately, the code isn't open source. I can try to create a small reproduction scenario, first, though, I was wondering if this is known/expected? Perhaps my assumptions about performance are incorrect?

**Comment by deivid-rodriguez** [comment]
Your assumptions are partially right. The debugger is supposed to have a performance penalty for sure, but in this particular case, it shouldn't happen and it's a bug.

This is what's left to be fixed from #144. Will close that issue and keep progress here. Also changed the title a bit, since what's serious and what's not is a bit subjective ;)

**Comment by jeffutter** [comment]
Ahh, good to see it's a known issue and not just me. I don't think I have much time to dig into this, but if there is any info I can provide, please let me know.

**Comment by maximderbin** [comment]
The same issue for me

**Comment by deivid-rodriguez** [comment]
Hi @jeffutter, @maximderbin and "plus-oners", this should be fixed by #406, feel free to give that branch a try and let me know. Thanks!

**Comment by jeffutter** [comment]
@deivid-rodriguez I'm no longer on a project where I need to use remote mode so I probably won't be able to give it a try. Hopefully, someone else can chime in. Thanks for the hard work though.

**Comment by deivid-rodriguez** [comment]
@jeffutter No problem at all, thanks for the kind words anyways!
