### ISSUE TITLE
Step out of current function call

### ISSUE THREAD

**Issue by garmoshka-mo** [deivid-rodriguez/byebug#304]
Wasn't able to find "Step out of current function call"
Analog of this in chrome javascript debugger:
<img width="145" alt="screen shot 2016-11-22 at 10 45 10" src="https://cloud.githubusercontent.com/assets/2452269/20516882/5425f9e8-b0a1-11e6-92ef-951b33b3f7c6.png">

**Comment by deivid-rodriguez** [comment]
You're looking for the `finish` command.

Regards.
