### ISSUE TITLE
update to readline 7

### ISSUE THREAD

**Issue by wintersolutions** [deivid-rodriguez/byebug#307]
## Problem description

GNU [readline 7 came out recently](http://cnswww.cns.cwru.edu/php/chet/readline/rltop.html#CurrentStatus). My arch based linux distribution already updated bash to a version where I need to have libreadline v. 7.0 installed. Other distributions will follow soon.

## Expected behavior

Use libreadline 6 or 7 ABI.

## Actual behavior

When I try to run a command like `spec` or `rails` I get errors like:

```
/home/foo_bar/.rvm/gems/ruby-2.3.1@b_hive/gems/byebug-9.0.6/lib/byebug/history.rb:2:in `require': libreadline.so.6: cannot open shared object file: No such file or directory - /home/foo_bar/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/x86_64-linux/readline.so (LoadError)
```

The file exists but its ```readline.so.7```.

## Steps to reproduce the problem

Update to readline v. 7.0 add `byebug` gem to a Gemfile. Run `bundle` and try to run a command that loads `byebug`.

**Comment by deivid-rodriguez** [comment]
You probably have to reinstall you ruby so it's linked against the new readline version.

```
rvm reinstall 2.3.1
```

(I don't remember the exact rvm syntax, but you can research that)

**Comment by wintersolutions** [comment]
@deivid-rodriguez thanks this works! I guess its a wrong filed bug report and can be closed.

**Comment by deivid-rodriguez** [comment]
I happy it worked! :)
