### ISSUE TITLE
hanoi.rb in GUIDE.md is too short

### ISSUE THREAD

**Issue by JunichiIto** [deivid-rodriguez/byebug#316]
I was reading GUIDE.md like a tutorial, but I found hanoi.rb immediately ended after hitting `restart 3`. This is because the sample code in GUIDE.md does not show all codes:

```ruby
#
# Solves the classic Towers of Hanoi puzzle.
#
def hanoi(n, a, b, c)
  hanoi(n - 1, a, c, b) if n - 1 > 0

  puts "Move disk #{a} to #{b}"

  hanoi(n - 1, c, b, a) if n - 1 > 0
end

n_args = $ARGV.length

fail('*** Need number of disks or no parameter') if n_args > 1

# I guess some other codes should continue...
```

I think the code would be like this:

http://www.thelackthereof.org/projects/school/csu/cs530/proj/gems/ruby/2.0.0/gems/byebug-2.7.0/test/examples/hanoi.rb

This issue is very surprising for byebug beginners like me, so could you list the full of the code?

**Comment by deivid-rodriguez** [comment]
@JunichiIto You're absolutely right, I opened #317 to fix this. Can you try if that program works ok?

**Comment by JunichiIto** [comment]
Okay, I will try it and inform you later.
