### ISSUE TITLE
pretty printing HTML on byebug interactive prompt

### ISSUE THREAD

**Issue by tansaku** [deivid-rodriguez/byebug#327]
Byebug is awesome.  I often find myself using it to debug issues with capybara in acceptance tests and I get to the interactive prompt like so:

```
[378, 387] in /Users/tansaku/Documents/GitHub/AgileVentures/WebsiteOne/features/step_definitions/basic_steps.rb
   378:     else
   379:       pending
   380:   end
   381:   page.driver.headers = { 'User-Agent' => agent }
   382: end
   383: 
   384: 
   385: And(/^I debug$/) do
   386:   byebug
=> 387: end
(byebug) page.body
```

and that allows me to dump the HTML that my server is responding with, but it comes back as a string like this:

```html
"<!DOCTYPE html><html><head>\n  <meta charset=\"utf-8\">\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<meta name=\"keywords\" content=\"AgileVentures, pair programming, crowdsourced learning\">\n<meta name=\"description\" content=\"AgileVentures is a project incubator that stimulates and su ...
````

which is great but it's often difficult to find things - what I'd love is to be able to print out the indented html from the interactive prompt.  

What I usually end up doing is copying the html into a text editor and then search through it, and/or post it into an online reformatter, but it would be so lovely to be able to get indented syntax colored html within byebug.

Now this is probably totally out of scope for byebug.  I've used thing like `y` and `ap` to display ruby objects more clearly at the terminal, but they don't work so well for HTML.  Does anyone have any tips for this?  Is there some formatting function or plugin for byebug?

The closest thing my google searches have turned up so far is this to import nokogiri etc.

http://stackoverflow.com/questions/1898829/how-do-i-pretty-print-html-with-nokogiri

many thanks in advance

**Comment by tansaku** [comment]
I wonder if I could use https://github.com/threedaymonk/htmlbeautifier ...

**Comment by deivid-rodriguez** [comment]
Yeah, I think this would be very useful but out of the scope of byebug. Did you figure it out? You would need some helper method that you can easily add to a project and evaluate that in byebug's prompt. Closing, anyways, but feel free to post your findings! :)
