### ISSUE TITLE
Using parameters that collide with byebug function names

### ISSUE THREAD

**Issue by dolan** [deivid-rodriguez/byebug#328]
## Problem description

When I'm in a byebug session debugging, any any context (rspec, app, or remote) I can't check on the status of parameters that are named 'source' because source is a command in byebug.

## Expected behavior

when I type 'source' I should see the contents of the 'source' parameter in the function I'm using.

## Actual behavior

it prints the help for the 'source' command

## Steps to reproduce the problem

```ruby

def frobnicate(source: , other:)
   byebug

end

```

and in the byebug console:
`(byebug) other` prints the contents of the 'other' parameter
`(byebug) source` prints 
```
  source <file>

  Restores a previously saved byebug session
```

**Comment by mmichael0413** [comment]
I think this is by design, but I agree that it's an issue and could be solved by adding a command to execute whichever line of code comes after it, despite naming collisions. Is there something like this in the works? If not, I may take a stab to address this issue.

**Comment by deivid-rodriguez** [comment]
Hi!

This is the same as doing `eval source`, `puts source`, and so on. What would be the difference between those and a new command?

**Comment by dolan** [comment]
I suppose that eval/puts are ok.  That certainly solves my problem.

**Comment by deivid-rodriguez** [comment]
Cool, let's leave it as it is now.
