### ISSUE TITLE
Invoking from within code fails

### ISSUE THREAD

**Issue by rpattcorner** [deivid-rodriguez/byebug#33]
Probably an error on my part, but ...

Invoking byebug from shell works fine, e.g.

byebug -- myprogram.rb --option1

However inserting the command

byebug

in ruby code results in, for example:

[root@ip-10-0-1-100 deploy]# ruby sshtest.bb.rb
sshtest.bb.rb:9:in `<main>': undefined local variable or method`byebug' for main:Object (NameError)

Code looks like:

[root@ip-10-0-1-100 deploy]# cat sshtest.bb.rb
require 'net/http'
require 'json'
require 'rexml/document'

require 'net/ssh'
require 'net/ssh/multi'

connect_fail_retries = 0;
byebug
begin
        puts "before do",connect_fail_retries
        ...

What obvious thing am I missing?
Documentation says to just insert

**Comment by meowsus** [comment]
@deivid-rodriguez I would recommend adding the _require 'byebug'_ bit to the documentation.

**Comment by tuxayo** [comment]
I fell in the same trap, however **require 'byebug'** failed with with a 'cannot load such file' error even thought the gem was installed. But adding it to the Gemfile worked.
