### ISSUE TITLE
MinGW, readline, RI2

### ISSUE THREAD

**Issue by MSP-Greg** [deivid-rodriguez/byebug#331]
Wasn't sure where to post this, but it's in response to your issue in RubyInstaller2.  Long story. I've been working on a MinGW build system that builds from a local repo (it uses quite a bit of code from RubyInstaller2).  I think I mentioned it in RI2, but a new readline package was released after there were issues found in Jan.

I've been building with it, and it passes all ruby tests except one.  I loaded byebug, using
```
ruby 2.5.0dev (2017-04-25 trunk 58476) [x64-mingw32]
```
and after forcing in `addressable`, ran `rake test`.  Output below --
```
  1) Skipped:
Byebug::PostMortemTest#test_execution_is_stopped_at_the_correct_line_after_exception [E:/GitHub/byebug/test/post_mortem_test.rb:49]:
See issue #165

  2) Skipped:
Byebug::RunnerAgainstValidProgramTest#test_run_with_no_quit_flag [E:/GitHub/byebug/test/runner_test.rb:131]:
Skipped, no message given

  3) Skipped:
Byebug::ListTest#test_lists_file_changes [E:/GitHub/byebug/test/commands/list_test.rb:192]:
Skipped, no message given

461 runs, 521 assertions, 0 failures, 0 errors, 3 skips
```
I don't use readline in any of my code, so I really don't know if it's working correctly.  Nor have I looked at your code to see what the three skips are about.

Do you recall if many of your tests are dependent on readline?

**Comment by deivid-rodriguez** [comment]
Hope you don't mind but I'll close here and move the discussion to oneclick/rubyinstaller2#36, just to keep the discussion in a single place, ok?
