### ISSUE TITLE
How to use byebug in a Ruby CGI script

### ISSUE THREAD

**Issue by philiprhoades** [deivid-rodriguez/byebug#332]
## Problem description

People,

Is it possible to do this?  I have byebug working fine in a CLI started script but how to get it working for a Ruby CGI script? (I couldn't find anything Googling . .).

Thanks,

Phil.

**Comment by deivid-rodriguez** [comment]
Hi! This seems more appropriate for a stackoverflow question, but you probably need to explore `byebug`'s remote debugging feature for what you want to achieve. Good luck!

**Comment by philiprhoades** [comment]
Why stackoverflow? Isn't this a Byebug thing? I will have a look for the remote debugging stuff but I didn't find anything when I was looking for something at the time . .

Thanks.
