### ISSUE TITLE
Cannot run rake routes when bybug start_server  is in effect

### ISSUE THREAD

**Issue by oystersauce8** [deivid-rodriguez/byebug#338]
I start byebug like this
```
.
  if ENV['USER'] == 'myusername'
    require 'byebug/core'
    #Byebug.wait_connection = true
    Byebug.start_server('localhost', 9999)
  end

end
```

I start my rails server like this .  `rails s`

Then when I do rake routes I get this error

```
$ bundle exec rake routes
rake aborted!
Errno::EADDRINUSE: Address already in use - bind(2) for "localhost" port 10000
```

**Comment by deivid-rodriguez** [comment]
I think this is expected. You're starting a remote debug server when starting Rails. When you run `rake routes`, the remote server is started again, but it has already been started when booting the server. I don't think you need remote debugging in this situation, put `byebug` wherever in the code you want to start debugging and you should be good to go!
