### ISSUE TITLE
incompatible library version ruby 2.3.1 and byebug 9.1.0 and bundler 1.11.2

### ISSUE THREAD

**Issue by ahmdelemam** [deivid-rodriguez/byebug#350]
## Problem description

Failure/Error: Bundler.require

LoadError:
  incompatible library version - /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/byebug-9.1.0/lib/byebug/byebug.so
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/byebug-9.1.0/lib/byebug/core.rb:2:in `require'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/byebug-9.1.0/lib/byebug/core.rb:2:in `<top (required)>'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-byebug-3.5.0/lib/byebug/processors/pry_processor.rb:1:in `require'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-byebug-3.5.0/lib/byebug/processors/pry_processor.rb:1:in `<top (required)>'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-byebug-3.5.0/lib/pry-byebug/pry_ext.rb:1:in `require'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-byebug-3.5.0/lib/pry-byebug/pry_ext.rb:1:in `<top (required)>'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-byebug-3.5.0/lib/pry-byebug/cli.rb:2:in `require'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-byebug-3.5.0/lib/pry-byebug/cli.rb:2:in `<top (required)>'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-0.10.4/lib/pry/plugins.rb:38:in `require'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-0.10.4/lib/pry/plugins.rb:38:in `load_cli_options'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-0.10.4/lib/pry/cli.rb:40:in `block in add_plugin_options'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-0.10.4/lib/pry/cli.rb:39:in `each'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-0.10.4/lib/pry/cli.rb:39:in `add_plugin_options'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-0.10.4/lib/pry/cli.rb:107:in `<top (required)>'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-0.10.4/lib/pry.rb:150:in `require'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-0.10.4/lib/pry.rb:150:in `<top (required)>'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-byebug-3.5.0/lib/pry-byebug.rb:1:in `require'
 /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/pry-byebug-3.5.0/lib/pry-byebug.rb:1:in `<top (required)>'
 ./spec/spec_helper.rb:4:in `<top (required)>'
 ./spec/api_spec.rb:1:in `require'
 ./spec/api_spec.rb:1:in `<top (required)>'

## Expected behavior

require byebug.

## Actual behavior

LoadError:
  incompatible library version - /home/ahmdelemam/.rvm/gems/ruby-2.3.1/gems/byebug-9.1.0/lib/byebug/byebug.so

## Steps to reproduce the problem

i am just using  ruby 2.3.1 and byebug 9.1.0 and bundler 1.11.2
when i try to rub test rspec i got the load error.

**Comment by deivid-rodriguez** [comment]
Hi @ahmdelemam. Thanks for the report. I don't know why that's happening unfortunately :disappointed: . I would try to upgrade `bundler` and `ruby` but I don't really have a lot of confidence on that fixing your issue.

If you could provide a sample application showing the problem I can have a look.

Also, could you please properly format the backtrace in the issue description? It's really hard to read copy-pasted like that.
