### ISSUE TITLE
How do you paste multiple lines of code?

### ISSUE THREAD

**Issue by ndbroadbent** [deivid-rodriguez/byebug#359]
I've been having a lot of frustration with `byebug`, because I can't paste multiple lines of code from my editor. Also, when I try to run `irb`, it doesn't have the same binding as the breakpoint. Is this a bug?

```ruby
irb(main):001:0> self
=> main
```

How can I paste multiple lines of code, for example to overwrite a method definition, or even just a multiline condition or case statement? I frequently do this in IRB, or in the Rails console, and would love to know if byebug can support this.

**Comment by ndbroadbent** [comment]
I've switched to using `binding.pry` with `pry-byebug`, and that's a much better experience. Also much better when I use [these aliases](https://github.com/deivid-rodriguez/pry-byebug#matching-byebug-behaviour) in my `~/.pryrc`.

Now the only remaining issue is that `binding.pry` is really long to type, and I want to make a shortcut. Is there anyway I can add a shorter alias to my `~/.pryrc`?

**Comment by deivid-rodriguez** [comment]
I figure this could be related to https://github.com/deivid-rodriguez/byebug/issues/367, so I'll close this and follow up in there. Regarding the question about aliases, I have no idea.

**Comment by stevecondylios** [comment]
+1 for this capability, if it were possible to paste in multiple lines of code, that would be very handy. Incidentally, I asked [here](https://stackoverflow.com/q/65057449/5783745) also.

@ndbroadbent is it possible to explain in a little more detail what you did to [improve the experience](https://github.com/deivid-rodriguez/byebug/issues/359#issuecomment-336139212) as I shall also try that (I haven't used any debugging software other than byebug, e.g. haven't used pry-byebug before)
