### ISSUE TITLE
NoMethodError (undefined method `step_out' for #<Byebug::Context:0x00000003c62f48>)

### ISSUE THREAD

**Issue by issei126** [deivid-rodriguez/byebug#360]
## Problem description

I get the error. The error message is on title. 
I found the same error in https://github.com/deivid-rodriguez/byebug/issues/200, but the error was not resolved.
The difference is I use Docker on mac os.

Rails 5.0.2
Ruby 2.4.1
byebug 9.1.0
Docker Version 17.09.0-ce-mac35 (19611)
mac os 10.12.6

**Comment by issei126** [comment]
I Reproduce the error.

Dockerfile
```
FROM ruby:2.4.1
RUN apt-get update -qq && \
 apt-get install -y build-essential libpq-dev curl && \
 curl -sL https://deb.nodesource.com/setup_4.x | bash - && \
 apt-get install -y nodejs && \
 mkdir /app
WORKDIR /app
ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
RUN bundle install
ADD . /app
```

Gemfile
```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '5.0.1'
gem 'sqlite3'
# Use sqlite3 as the database for Active Record
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  gem 'debase', "0.2.1"
  gem 'ruby-debug-ide', "0.6.0"
end
```

application code
```
class TopController < ApplicationController
  def index
    byebug
  end
end
```

Then, I try to access `localhost:3000/top/index`, The error blow raises.
```
Completed 500 Internal Server Error in 464ms (ActiveRecord: 0.0ms)



NoMethodError (undefined method `step_out' for #<Byebug::Context:0x007fa4608278d0>):

app/controllers/top_controller.rb:3:in `index'
```

Please give me an advise.
Thanks.

**Comment by tomaszwojcik** [comment]
Same issue here, my specs:

* Rails 5.0.4
* Ruby 2.4.1p111
* byebug 9.1.0
* Docker Version 17.09.0-ce-mac35 (19611)
* macOS 10.13.1 (17B48)

**Comment by deivid-rodriguez** [comment]
Sorry I never got to answer this. `Byebug` is incompatible with `debase`.

**Comment by ducnguyenhuy** [comment]
I got the same issue and I'm not using debase gem. Any suggestion please?
