### ISSUE TITLE
New command to continue and never stop again

### ISSUE THREAD

**Issue by cyrilchampier** [deivid-rodriguez/byebug#366]
## Problem description

Put a `byebug`  in a loop, execute code.
You will be stuck with a choice: 
* 'continue' X times to get out of the loop
* 'exit-program' to end the whole execution

## Expected behavior

Add a third option:
'continue_always' that would continue, and never break again (if possible only in this breakpoint)

**Comment by Frexuz** [comment]
+1000 👍  :D

**Comment by deivid-rodriguez** [comment]
This has been fixed by the new commands `continue!` (and never break again) and `skip` (further instances of the current breakpoint, but not other breakpoints).
