### ISSUE TITLE
The tests are broken?

### ISSUE THREAD

**Issue by tacnoman** [deivid-rodriguez/byebug#370]
## Problem description

Hello guys. I'm developing the issue #366, but many tests are broken when I try to run.
I forked the project and started developing this feature. Now I want to write some tests and make the PR, but when I run this is the result:

`469 runs, 533 assertions, 59 failures, 0 errors, 3 skips`
I came back some commits and try again, but happen the same behavior.

This is a problem in my configuration or the project has tests broke?

I ran:

```bash
$ bundle install
$ bundle exec rake compile
$ bundle exec rake test
```

## Expected behavior

All tests fixed.

## Actual behavior

`469 runs, 533 assertions, 59 failures, 0 errors, 3 skips`

## Steps to reproduce the problem

I ran:

```bash
$ bundle install
$ bundle exec rake compile
$ bundle exec rake test
```

One example of test broke and the result
```
 59) Failure:
Byebug::UpTest#test_up_skips_c_frames [/private/var/www/byebug/byebug/test/support/matchers.rb:27]:
Expected ["",
 "[11, 20] in /private/var/folders/7v/pydr1l5n0zg0_qpkl4b727p40000gn/T/byebug_test.rb",
 "11:       integerize(str + 'x') + 5",
 "12:     end",
 "13:",
 "14:     def integerize(str)",
 "15:       byebug",
 "=> 16:       str.ord",
 "17:     end",
 "18:   end",
 "19:",
 "20:   frame = ByebugTestClass.new('f')",
 "(byebug)",
 "",
 "[14, 23] in /private/var/folders/7v/pydr1l5n0zg0_qpkl4b727p40000gn/T/byebug_test.rb",
 "14:     def integerize(str)",
 "15:       byebug",
 "16:       str.ord",
 "17:     end",
 "18:   end",
 "19:",
 "=> 20:   frame = ByebugTestClass.new('f')",
 "21:",
 "22:   frame",
 "23: end",
 "(byebug)",
 "--> #4  <module:Byebug> at /private/var/folders/7v/pydr1l5n0zg0_qpkl4b727p40000gn/T/byebug_test.rb:20",
 "(byebug)"]
 to include [/--> #4  <module:Byebug> at \/var\/folders\/7v\/pydr1l5n0zg0_qpkl4b727p40000gn\/T\/byebug_test.rb:20/]
 in order.

469 runs, 533 assertions, 59 failures, 0 errors, 3 skips
```

**Comment by deivid-rodriguez** [comment]
Hei @tacnoman! Thanks so much for wanting to help out `byebug`! :heart:

Tests should be passing in general, see the [build status](https://github.com/deivid-rodriguez/byebug#build-status) in the README. So it must be something about your environment.

Some guesses from past experience:

* Your dev folder might be "too deep" and that causes the bug?
* Your dev folder might contain a symlink and that causes the bug?

Could you double check these ideas?

**Comment by tacnoman** [comment]
Hello @deivid-rodriguez 
I'm running in Mac Os, but now I'm running in Docker and all works :D
Thanks for this

**Comment by bak1an** [comment]
@tacnoman #373 is there to fix this
