### ISSUE TITLE
We still need support for ruby 2.0

### ISSUE THREAD

**Issue by otheus** [deivid-rodriguez/byebug#402]
## Problem description

Ruby 2.0 needs an actual CLI debugger still (not this pry crap). RedHat 7, (the largest server installation base) deploys Ruby 2.0. Upgrading to newer versions of ruby is both painful, dangerous, and impractical. These deployments need an actual interactive debugger (which I do consider pry to be a usable example of). "ruby-debug" support seems to have stopped with 1.9.3, and 'byebug' is said to superceded 'debugger'. But 'gem install byebug' reports that ruby 2.2 is required, despite widespread internet discussions to the contrary. 

## Expected behavior

Please continue to support Ruby 2.0 or provide easy-to-find documentation for a work-around.

**Comment by deivid-rodriguez** [comment]
Can you try `gem install byebug -v 9.0.6`?

**Comment by deivid-rodriguez** [comment]
I recommend you request RedHat 7 to upgrade the ruby version they ship, ruby 2.0 and ruby 2.1 are EOL'd. Thanks.

**Comment by otheus** [comment]
Thank you -- success with 1 error/warning:

```
unable to convert "\xD0" from ASCII-8BIT to UTF-8 for lib/byebug/byebug.so, skipping
```

Hopefully now that I've created this issue, others will be able to search the internet and find it.

**Comment by deivid-rodriguez** [comment]
You're welcome, I'm happy that the workaorund works for you.

**Comment by otheus** [comment]
@deivid-rodriguez  <rant> A word of advice: Ruby (and many other software projects) are in the wrong by having such short-lived version lifecycles/lifetimes. Operating Systems, whether they be RedHat or Windows or MacOS need to be supportable for at least 10 years from release, which means the software they deploy needs to be supported for much longer than that. Every time Ruby or Python releases a new version, they depracate or outmode some feature that a large software stack depends on. While the bundle system gets around this to some extent, it's impractical and wasteful to rely on bundling for every tool.  This adherence and understanding of a long-term view is a big reason why perl and bash and C are so successful, and why I fear ruby will be dead before you know it. The language is cool, but the lifecycle strategy is horrible.  </rant>

**Comment by otheus** [comment]
<rant page="2"> FYI, I still have a few RHEL6 systems and even RHEL5 systems which I must support. Two years ago, I was developing code which had to run on RHEL6, which (TBMI) supported only Ruby 1.8.3. Imagine trying to simultaneously develop -- and debug -- something for ruby 1.8 and ruby 2.0! </rant>
