### ISSUE TITLE
Rails debugging - byebug starts on production environment

### ISSUE THREAD

**Issue by ey123** [deivid-rodriguez/byebug#41]
If I forget a "byebug" command in the code and it gets deployed to production, byebug stops on the breakpoint.

When I used debugger gem it used to skip "debugger" commands.
I tried Byebug.stop() in config/environments/production.rb - didn't work.

Is there any way I can make byebug disabled for production?

Thanks.

**Comment by Alphabetus** [comment]
> The truth is I don't feel like spending time now on babysitting developers. Maybe you can override `byebug`'s method and check for the environment there...

Just came here to point the magnificent reply you posted here. 
I have no words for that comment. You must be a true gent.
