### ISSUE TITLE
Can't set breakpoints on line numbers

### ISSUE THREAD

**Issue by stevewi** [deivid-rodriguez/byebug#424]
## Problem description

Whenever I try to set a breakpoint on a line number, I get this:

(byebug) b 99
*** Line 99 is not a valid breakpoint in file <...>.rb

## Expected behavior

Note line 99 would be the next line in the file reachable by 'next'.  I would expect byebug to be able to set a breakpoint there.

## Actual behavior

See the above problem description.

## Steps to reproduce the problem

This happens for me every time and seems to have started when I moved from 2.4.x to 2.5.0.  It happens on every installation I have -- macOS and Linux.

This might be an installation issue.  I have byebug installed as a global gem on my Linux boxes and as a local gem on macOS.  All the Linux boxes are Ubuntu 16.04.  Ruby on Linux is 2.5.0 installed from the source distribution from ruby-lang.org.  macOS Ruby is 2.5.0 and was installed via 'RBENV'.  

I'd appreciate any help any of you might be able to give on this.  This used to work and it's hampering the usefulness of byebug for me considerably.
  
TIA.

**Comment by deivid-rodriguez** [comment]
Hi, @stevewi!

This is a change in behavior in ruby 2.5 indeed. Have a look at https://github.com/deivid-rodriguez/byebug/issues/345 for more context. Now you should set the breakpoint on the first line of the method instead. If you point to latest byebug master, you will get a friendly error message telling you the available breakpoint locations, have a look at #393 for more info about that.
