### ISSUE TITLE
Tests randomly hang

### ISSUE THREAD

**Issue by deivid-rodriguez** [deivid-rodriguez/byebug#428]
## Problem description

After merging #406, some tests hang. In particular, [this CircleCI job](https://circleci.com/gh/deivid-rodriguez/byebug/2901) (which belong to [this workflow](https://circleci.com/workflow-run/9e0b3897-3c3a-4db9-93dc-d03eef75aef4)), and [this Appveyor job](https://ci.appveyor.com/project/deivid-rodriguez/byebug/build/job/vld0pn9jlmcv9g85) (which belongs to [this build](https://ci.appveyor.com/project/deivid-rodriguez/byebug/build/1.0.1122)). At first sight, it doesn't look platform specific, not sure if it affects tests only or real usage too.
 
## Expected behavior

All tests pass, always.

## Actual behavior

Tests hang.

## Steps to reproduce the problem

None, currently. Seems like one of the hardest parts to fix the issue.

**Comment by MSP-Greg** [comment]
@deivid-rodriguez

I'll see if I can repo locally, probably tomorrow.  Thanks, Greg

**Comment by deivid-rodriguez** [comment]
Reopening since something not right seems to be still going on, see: https://ci.appveyor.com/project/deivid-rodriguez/byebug/build/1.0.1136

**Comment by deivid-rodriguez** [comment]
Another example: https://ci.appveyor.com/project/deivid-rodriguez/byebug/build/1.0.1138.
