### ISSUE TITLE
Installation trouble Windows 10

### ISSUE THREAD

**Issue by kartikvips** [deivid-rodriguez/byebug#436]
PS C:\Users\kkpar> gem install byebug
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing byebug:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/byebug-10.0.0/ext/byebug
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20180222-8836-106pbui.rb extconf.rb
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/byebug-10.0.0/ext/byebug
make "DESTDIR=" clean

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/byebug-10.0.0/ext/byebug
make "DESTDIR="
generating byebug-x64-mingw32.def
make: *** No rule to make target `/C/Ruby24-x64/include/ruby-2.4.0/ruby.h', needed by `breakpoint.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/byebug-10.0.0 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/byebug-10.0.0/gem_make.out

--Versions--
gem v2.7.6
ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
Windows 10

**Comment by MSP-Greg** [comment]
@kartikvips

I'll have to look at it tomorrow, but I just installed 10.0.0 using the same Ruby version, and it installed fine.  Do you know if you've installed any other extension gems?  Puma, Nokigiri, Thin, EventMachine, etc.

**Comment by kartikvips** [comment]
I don't have any of the ones you mentioned installed. Here's a list of the gems that are installed. 

*** LOCAL GEMS ***

bigdecimal (default: 1.3.0)
bundler (default: 1.16.1, 1.15.4)
coderay (1.1.2)
did_you_mean (1.1.0)
diff-lcs (1.3)
io-console (default: 0.4.6)
json (default: 2.0.4)
method_source (0.9.0)
minitest (5.10.1)
net-telnet (0.1.1)
openssl (default: 2.0.5)
power_assert (0.4.1)
pry (0.11.3)
psych (default: 2.2.2)
rake (12.0.0)
rdoc (default: 5.0.0)
rspec (3.7.0)
rspec-core (3.7.0)
rspec-expectations (3.7.0)
rspec-mocks (3.7.0)
rspec-support (3.7.0)
rubygems-update (2.7.6, 2.6.14)
test-unit (3.2.3)
xmlrpc (0.2.1)

**Comment by MSP-Greg** [comment]
@kartikvips

I think there's any extension gems there.  What's the output from `ridk version`?

To install extension gems, everything has to be correct with your MSYS2 install.  I've never had issues with mine, so I've never needed to dig around much...

You might try
```
gem install byebug -- --use-system-libraries
```

**Comment by kartikvips** [comment]
i tried the -- --use-system-libraries and got the same error

Here's the output from ridk version

ruby:
  path: C:/Ruby24-x64
  version: 2.4.2
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.2-2
  git_commit: a1b07ad
msys2:
  path: C:\msys64
  title: MSYS2 64bit
  version: '20161025'
sh: GNU bash, version 4.3.46(2)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.15063]

**Comment by MSP-Greg** [comment]
It seems that the compiler isn't installed, as your msys2 section should be something similar to;
```
msys2:
  path: c:\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: x86_64-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 7.3.0
sh: GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
```
I think you can do `ridk install 2 3` to do so.  Then try to install the gem.

**Comment by kartikvips** [comment]
Ah. So the issue was that the ridk install was not being completed because the update (2) was failing for some reason. So I just did ridk install 3 and the byebug install worked fine after that.

Thanks!!

**Comment by MSP-Greg** [comment]
@kartikvips

You might open an MSYS2 console and enter `pacman -Syuu`.  There maybe some screen prompts about closing the console with an Alt-F4 or mouse then running again.
