### ISSUE TITLE
Feature Request: Ability to specify a location other than current dir for .byebug_history

### ISSUE THREAD

**Issue by oystersauce8** [deivid-rodriguez/byebug#577]
## Problem description

Having a way to generate the .byebug_history at a different location saves
us from having to .gitignore it

Related 
https://stackoverflow.com/questions/45096761/how-do-you-change-byebug-history-location

**Comment by gabrielmdeal** [comment]
FYI, I submitted an answer to [that StackOverflow question](https://stackoverflow.com/questions/45096761/how-do-you-change-byebug-history-location).  I think you're looking for `set histfile /some/file` in `~/.byebugrc`.

**Comment by deivid-rodriguez** [comment]
Indeed, you can use `set histfile` for this. Thanks for the help @gabrielmdeal, closing!
