### ISSUE TITLE
byebug not installable under ruby 2.7.0

### ISSUE THREAD

**Issue by paradoxon82** [deivid-rodriguez/byebug#651]
## Problem description

When installing the gem I get the following error:
[gem_make.out.txt](https://github.com/deivid-rodriguez/byebug/files/4205490/gem_make.out.txt)

These unrecognized commands (like -Wno-self-assign) seem to be specific to clang and not gcc.
But the Makefile specifies gcc as the compiler.

Am I missing something?

## Expected behavior

gem installed

## Actual behavior

compiler error

## Steps to reproduce the problem

bundle install

**Comment by deivid-rodriguez** [comment]
How are you installing byebug? The log shows a very old version, which I don't really expect to work on ruby 2.7. Also I suspect the version of `rvm` you're using is very old as well.

**Comment by paradoxon82** [comment]
Ok, thanks.
I will check it next week.


David Rodríguez <notifications@github.com> schrieb am Fr., 14. Feb. 2020,
18:04:

**Comment by paradoxon82** [comment]
Hi again,
I don't know why I had such an old version in my gemspec file.
Now installation worked, thanks!
