### ISSUE TITLE
'up' after 'step' keeps drilling down on 'next'

### ISSUE THREAD

**Issue by elado** [deivid-rodriguez/byebug#85]
If I `step` into a method and then `up`, when I execute `next` it goes back to what `next` would be if I didn't hit `up`. My intention is to go back to the original stacktrace but it keeps going back to the one I stepped into.

The only way I can get away from it is to add a breakpoint somewhere else and `cont`.

It's been like that for a long time.

MRI Ruby 2.1.2, buybug 3.5.0.

**Comment by elado** [comment]
@deivid-rodriguez as asked on #102 I'm still experiencing it, all the time. It's a big project but I'll find some time to isolate it.

**Comment by deivid-rodriguez** [comment]
So why open a new issue to workaround the problem instead of answering the question asked 3 months ago? It's really discouraging when people open issues and never reply to them.  :-1:  :disappointed:

**Comment by elado** [comment]
Here it is: https://github.com/elado/byebug-issue

It happens during RSpec (but I recall it happened in multiple places).
Look at `log.log` to see the flow - how many `up` I need to run just to step into `bar` method.

Running on 2.2.0 MRI.

**Comment by deivid-rodriguez** [comment]
So basically you expect (after having learned that `foo` is a generated method) that the sequence `step`, `up`, `step` will take you to `bar`, right? I think that makes sense, I'll have a look.

Just to confirm, you keep refering to the `step`, `up`, `next` sequence (in both the title and your last sentence) but this issue has nothing to do with `next`, right?

**Comment by deivid-rodriguez** [comment]
Give last master a try and let me know!

**Comment by elado** [comment]
Perfect, awesome!
The `next` was related to this as it doesn't happen anymore. Thank you very much.

**Comment by deivid-rodriguez** [comment]
Your are welcome! Cheers! :smile:
