### ISSUE TITLE
Entire source file is one line

### ISSUE THREAD

**Issue by toddh** [deivid-rodriguez/byebug#91]
Hello!

Great looking tool.

I'm having a problem I'm hoping you can help me with. Byebug seems to lose all concept of lines. This happens to me in my rails helpers when I break with either a breakpoint or the byebug command. (I'm really trying to debug a gem.)

If I step into the helper, things seem to work OK. But using a breakpoint or the byebug command doesn't. In this case, it brings up the right source file -- but displays the *entire* file. I tried setting a breakpoint and I get "There are only 1 lines in file /Users/todd/portfolio/app/helpers/import_helper.rb."

I was in a file and everything looked good. I set a breakpoint down about a 100 lines and pressed continue. When byebug broke, I no longer had any line number -- just one giant line.

I've tried this on OSX and LINUX and get the same behavior.

I'm running ruby 2.1.3, rails 4.1.0, and byebug 3.5.1.

Thanks in advance for any help.

**Comment by deivid-rodriguez** [comment]
Closing for lack of feedback, feel free to reopen if you still can reproduce this.
