### ISSUE TITLE
Upgrade to slop 4.0.0

### ISSUE THREAD

**Issue by jcoyne** [deivid-rodriguez/byebug#99]

**Comment by jcoyne** [comment]
Nice!

**Comment by nathankleyn** [comment]
I just wanted to express my thanks for this, @deivid-rodriguez, as I'm in the situation right now where I can't use the stable because it depends on `slop` < 4 (and this conflicts with my app's dependency on 4.0.0). Saved me a bunch of painful debugging using something else!

**Comment by deivid-rodriguez** [comment]
:+1: Glad to help, I hope to release soon so you guys don't need to use master.
